-- ═══ DnB +8 (anchor: tom kw bright,organic,lush,wide,room → }}, -- Electronica)

    { name="Ragga", default_kw={"heavy","bright","punch","synthetic","machine","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","punch","bright","sub","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","bright","sub","punch"}},
        snare    ={type="Snare Electronic", kw={"bright","heavy","punch","synthetic","snap"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","heavy","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","heavy","snap","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","machine"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","heavy","machine"}},
        crash    ={type="Crash",            kw={"bright","synthetic","heavy","wide"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","machine","synthetic"}},
        tom      ={type="Tom",              kw={"heavy","punch","bright","wide","deep"}},
      },
    },
    { name="Drumfunk", default_kw={"organic","lofi","tape","punch","creative","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","lofi","vintage"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","room","lofi"}},
        snare    ={type="Snare Acoustic",   kw={"punch","organic","room","lofi","bright"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","punch","tape"}},
        clap     ={type="Claps & Snaps",    kw={"organic","room","bright","lofi","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","organic","lofi"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","organic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","bright","organic","room"}},
        crash    ={type="Crash",            kw={"organic","room","bright","acoustic"}},
        ride     ={type="Ride",             kw={"acoustic","bright","organic"}},
        perc     ={type="Shakers",          kw={"organic","acoustic","bright","room"}},
        tom      ={type="Tom",              kw={"punch","organic","lofi","room","deep"}},
      },
    },
    { name="Vintage Jungle", default_kw={"lofi","tape","vinyl","punch","heavy","bright"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","heavy","lofi","tape","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","lofi","organic","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","lofi","tape","heavy"}},
        snare_alt={type="Snare Electronic", kw={"heavy","lofi","snap","punch"}},
        clap     ={type="Claps & Snaps",    kw={"lofi","heavy","snap","punch","tape"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","bright","metallic","tape"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","metallic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","bright","metallic","heavy"}},
        crash    ={type="Crash",            kw={"lofi","bright","metallic","heavy"}},
        ride     ={type="Ride",             kw={"lofi","metallic","bright"}},
        perc     ={type="Shakers",          kw={"organic","lofi","bright","tape"}},
        tom      ={type="Tom",              kw={"heavy","lofi","punch","deep","tape"}},
      },
    },
    { name="Crossbreed", default_kw={"hard","heavy","noise","synthetic","industrial","dark"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","heavy","sub","noise","industrial"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","noise","dark"}},
        snare    ={type="Snare Electronic", kw={"hard","noise","heavy","industrial","snap"}},
        snare_alt={type="Snare Electronic", kw={"noise","hard","heavy","industrial"}},
        clap     ={type="Claps & Snaps",    kw={"hard","noise","heavy","industrial","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","hard","noise","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","noise","hard"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","noise","heavy","hard"}},
        crash    ={type="Crash",            kw={"noise","metallic","hard","industrial"}},
        ride     ={type="Ride",             kw={"metallic","noise","hard"}},
        perc     ={type="Perc Electronic",  kw={"noise","hard","metallic","industrial"}},
        tom      ={type="Tom",              kw={"hard","heavy","noise","industrial","deep"}},
      },
    },
    { name="Jazz Step", default_kw={"organic","bright","room","soft","gold","acoustic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","organic","bright","room","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","soft","gold"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","soft","flam"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","room","soft","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","gold"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","soft"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","soft"}},
        tom      ={type="Tom",              kw={"organic","room","bright","soft","deep"}},
      },
    },
    { name="Cinematic", default_kw={"wide","lush","organic","room","layered","bright"},
      voices={
        kick     ={type="Kick Electronic",  kw={"wide","deep","sub","organic","layered"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","room","organic","heavy","deep"}},
        snare    ={type="Snare Acoustic",   kw={"wide","bright","room","organic","layered"}},
        snare_alt={type="Snare Electronic", kw={"wide","layered","bright","organic"}},
        clap     ={type="Claps & Snaps",    kw={"wide","bright","organic","room","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","wide","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","wide","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","wide","organic","room"}},
        crash    ={type="Crash",            kw={"wide","bright","organic","room","mallet"}},
        ride     ={type="Ride",             kw={"bright","acoustic","wide","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","wide","acoustic","lush"}},
        tom      ={type="Tom",              kw={"wide","deep","organic","layered","room"}},
      },
    },
    { name="Dancefloor", default_kw={"punch","bright","wide","synthetic","machine","heavy"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","sub","wide","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","heavy","sub","bright"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","wide","snap","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","wide","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","snap","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","machine","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","machine","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","heavy"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","heavy"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","machine"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","wide","synthetic","machine"}},
        tom      ={type="Tom",              kw={"punch","wide","bright","heavy","deep"}},
      },
    },
    { name="Autonomic", default_kw={"soft","deep","organic","synthetic","wide","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","deep","sub","organic","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","organic","sub","layered"}},
        snare    ={type="Snare Electronic", kw={"soft","organic","layered","synthetic","wide"}},
        snare_alt={type="Snare Electronic", kw={"soft","layered","organic","wide"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","wide","layered","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","synthetic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","bright","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","synthetic","wide","organic"}},
        crash    ={type="Crash",            kw={"soft","wide","organic","mallet","layered"}},
        ride     ={type="Ride",             kw={"soft","synthetic","organic","wide"}},
        perc     ={type="Shakers",          kw={"organic","soft","wide","acoustic"}},
        tom      ={type="Tom",              kw={"deep","soft","organic","sub","wide"}},
      },
    },

-- ═══ ELECTRONICA +9 (anchor: tom kw lofi,tape,dark,organic,vintage → }}, -- Lo-Fi)

    { name="Industrial", default_kw={"hard","metallic","noise","machine","dark","heavy"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","industrial","heavy","noise","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","noise","heavy","dark"}},
        snare    ={type="Snare Electronic", kw={"hard","metallic","noise","machine","heavy"}},
        snare_alt={type="Snare Electronic", kw={"metallic","noise","hard","industrial"}},
        clap     ={type="Claps & Snaps",    kw={"hard","noise","machine","heavy","industrial"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","noise","hard","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","noise","machine"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","noise","heavy","hard"}},
        crash    ={type="Crash",            kw={"noise","metallic","hard","machine","dark"}},
        ride     ={type="Ride",             kw={"metallic","noise","machine","dark"}},
        perc     ={type="Perc Electronic",  kw={"metallic","noise","machine","hard"}},
        tom      ={type="Tom",              kw={"heavy","hard","noise","industrial","dark"}},
      },
    },
    { name="Noise Music", default_kw={"noise","creative","metallic","dark","heavy","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"noise","heavy","dark","synthetic","creative"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","dark","heavy","creative"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","metallic","heavy","dark"}},
        snare_alt={type="Snare Electronic", kw={"noise","creative","metallic","dark"}},
        clap     ={type="Claps & Snaps",    kw={"noise","heavy","creative","dark","metallic"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","metallic","dark","creative"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","metallic","dark"}},
        hh_o     ={type="HiHat Open",       kw={"noise","heavy","metallic","dark"}},
        crash    ={type="Crash",            kw={"noise","creative","metallic","heavy","dark"}},
        ride     ={type="Ride",             kw={"noise","metallic","creative","dark"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","metallic","dark"}},
        tom      ={type="Tom",              kw={"noise","dark","heavy","creative","deep"}},
      },
    },
    { name="Broken Beat", default_kw={"organic","tight","punch","bright","creative","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","organic","bright","tight","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","punch","snap"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","punch","organic","tight"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","snap","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","tight"}},
        crash    ={type="Crash",            kw={"bright","organic","room","creative","acoustic"}},
        ride     ={type="Ride",             kw={"bright","acoustic","organic","tight"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","organic","creative","tight"}},
        tom      ={type="Tom",              kw={"punch","organic","bright","tight","room"}},
      },
    },
    { name="Braindance", default_kw={"creative","synthetic","noise","bright","machine","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"synthetic","punch","creative","bright","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"synthetic","creative","noise","punch"}},
        snare    ={type="Snare Electronic", kw={"creative","synthetic","noise","bright","snap"}},
        snare_alt={type="Snare Electronic", kw={"creative","noise","synthetic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"creative","bright","noise","synthetic","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","creative","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","creative"}},
        hh_o     ={type="HiHat Open",       kw={"synthetic","creative","noise","bright"}},
        crash    ={type="Crash",            kw={"creative","noise","synthetic","bright","metallic"}},
        ride     ={type="Ride",             kw={"synthetic","creative","noise","bright"}},
        perc     ={type="Perc Glitch",      kw={"creative","noise","synthetic","bright"}},
        tom      ={type="Tom",              kw={"synthetic","creative","noise","deep","punch"}},
      },
    },
    { name="Skweee", default_kw={"bright","synthetic","machine","organic","snap","warm"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","synthetic","machine","organic"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","machine","organic","punch"}},
        snare    ={type="Snare Electronic", kw={"bright","synthetic","snap","machine","organic"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","organic","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","synthetic","organic","machine"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","machine","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","machine","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","machine","organic"}},
        crash    ={type="Crash",            kw={"bright","synthetic","organic","machine"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","synthetic","organic","machine"}},
        tom      ={type="Tom",              kw={"organic","punch","bright","synthetic","warm"}},
      },
    },
    { name="Deconstructed", default_kw={"noise","creative","hard","synthetic","dark","metallic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"noise","creative","hard","synthetic","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","dark","hard","creative"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","hard","metallic","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"creative","noise","metallic","hard"}},
        clap     ={type="Claps & Snaps",    kw={"noise","creative","hard","metallic","dark"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","metallic","dark","creative","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","metallic","dark","creative"}},
        hh_o     ={type="HiHat Open",       kw={"noise","metallic","heavy","dark","creative"}},
        crash    ={type="Crash",            kw={"noise","creative","metallic","dark","hard"}},
        ride     ={type="Ride",             kw={"noise","metallic","dark","creative"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","hard","metallic"}},
        tom      ={type="Tom",              kw={"noise","dark","hard","creative","heavy"}},
      },
    },
    { name="Microsound", default_kw={"soft","tight","organic","synthetic","bright","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","tight","organic","synthetic","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","organic","tight","bright"}},
        snare    ={type="Snare Electronic", kw={"soft","tight","bright","organic","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"soft","bright","tight","organic"}},
        clap     ={type="Claps & Snaps",    kw={"soft","tight","bright","organic","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","tight","bright","acoustic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","tight","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","acoustic","organic"}},
        crash    ={type="Crash",            kw={"soft","bright","organic","mallet","wide"}},
        ride     ={type="Ride",             kw={"soft","bright","acoustic","organic"}},
        perc     ={type="Perc Electronic",  kw={"soft","snap","bright","tight","organic"}},
        tom      ={type="Tom",              kw={"soft","organic","tight","wide","bright"}},
      },
    },
    { name="Plunderphonics", default_kw={"lofi","tape","vinyl","organic","creative","vintage"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"lofi","vintage","organic","punch","tape"}},
        kick_alt ={type="Kick Electronic",  kw={"lofi","organic","vintage","punch"}},
        snare    ={type="Snare Acoustic",   kw={"lofi","organic","room","bright","tape"}},
        snare_alt={type="Snare Acoustic",   kw={"lofi","bright","organic","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"lofi","organic","bright","tape","creative"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","acoustic","bright","tape","vintage"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","acoustic","vintage"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","acoustic","bright","tape"}},
        crash    ={type="Crash",            kw={"lofi","organic","bright","vintage"}},
        ride     ={type="Ride",             kw={"lofi","acoustic","bright","vintage"}},
        perc     ={type="Shakers",          kw={"organic","lofi","bright","acoustic"}},
        tom      ={type="Tom",              kw={"lofi","organic","vintage","punch","tape"}},
      },
    },
    { name="Electro Industrial", default_kw={"hard","machine","synthetic","noise","metallic","dark"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","machine","synthetic","heavy","noise"}},
        kick_alt ={type="Kick Electronic",  kw={"machine","hard","heavy","noise"}},
        snare    ={type="Snare Electronic", kw={"hard","machine","metallic","synthetic","noise"}},
        snare_alt={type="Snare Electronic", kw={"machine","metallic","hard","noise"}},
        clap     ={type="Claps & Snaps",    kw={"hard","machine","noise","metallic","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","machine","hard","tight","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","machine","hard","noise"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","machine","heavy","noise"}},
        crash    ={type="Crash",            kw={"metallic","noise","machine","hard","dark"}},
        ride     ={type="Ride",             kw={"metallic","machine","noise","dark"}},
        perc     ={type="Perc Electronic",  kw={"machine","metallic","noise","hard","snap"}},
        tom      ={type="Tom",              kw={"heavy","machine","hard","noise","dark"}},
      },
    },

-- ═══ LO-FI +10 (anchor: tom kw room,organic,punch,warm,vintage → }}, -- Pop & Disco)

    { name="Lo-Fi RnB", default_kw={"organic","warm","soft","lush","vintage","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","organic","warm","deep","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","room","organic","punch"}},
        snare    ={type="Snare Acoustic",   kw={"warm","soft","organic","room","bright"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","warm","organic","room","soft"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","warm","lush","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","acoustic","organic","warm","bright"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","warm","organic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","organic","warm","room"}},
        crash    ={type="Crash",            kw={"soft","organic","room","warm","lush"}},
        ride     ={type="Ride",             kw={"soft","acoustic","warm","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","warm","acoustic","lush"}},
        tom      ={type="Tom",              kw={"soft","organic","warm","room","deep"}},
      },
    },
    { name="Crate Digger", default_kw={"vinyl","dirty","organic","room","bright","vintage"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","vintage","dirty"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","vintage","dirty"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","dirty","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","vintage","room","flam"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","vintage","dirty","room"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","vintage","organic","lofi"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","vintage","organic"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","bright","vintage","organic"}},
        crash    ={type="Crash",            kw={"organic","bright","vintage","room"}},
        ride     ={type="Ride",             kw={"acoustic","vintage","bright","organic"}},
        perc     ={type="Shakers",          kw={"organic","acoustic","vintage","bright"}},
        tom      ={type="Tom",              kw={"organic","punch","vintage","dirty","room"}},
      },
    },
    { name="City Pop", default_kw={"bright","lush","warm","organic","vintage","disco"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","sub","lush","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","bright","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","lush","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","warm","organic","room","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","lush","warm","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic","warm"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","warm","gold"}},
        crash    ={type="Crash",            kw={"bright","organic","lush","warm","room"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","warm"}},
        perc     ={type="Shakers",          kw={"organic","bright","warm","acoustic","lush"}},
        tom      ={type="Tom",              kw={"bright","organic","warm","lush","room"}},
      },
    },
    { name="Reverb Rap", default_kw={"room","organic","lofi","punch","warm","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","room","organic","sub","lofi"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"room","organic","bright","wide","lofi"}},
        snare_alt={type="Snare Acoustic",   kw={"room","organic","wide","bright","flam"}},
        clap     ={type="Claps & Snaps",    kw={"room","organic","bright","wide","lofi"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","lofi","bright","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","lofi","organic"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","room","bright","organic"}},
        crash    ={type="Crash",            kw={"room","organic","bright","wide"}},
        ride     ={type="Ride",             kw={"acoustic","room","bright","organic"}},
        perc     ={type="Shakers",          kw={"organic","room","bright","acoustic"}},
        tom      ={type="Tom",              kw={"room","organic","wide","punch","lofi"}},
      },
    },
    { name="Woozy", default_kw={"soft","lofi","tape","organic","warm","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","lofi","organic","warm","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","lofi","organic","punch"}},
        snare    ={type="Snare Acoustic",   kw={"soft","lofi","organic","warm","bright"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","organic","warm","lofi","bright"}},
        clap     ={type="Claps & Snaps",    kw={"soft","lofi","organic","warm","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","lofi","acoustic","organic","warm"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","lofi","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","lofi","acoustic","organic"}},
        crash    ={type="Crash",            kw={"soft","organic","lofi","mallet","warm"}},
        ride     ={type="Ride",             kw={"soft","acoustic","lofi","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","lofi","warm"}},
        tom      ={type="Tom",              kw={"soft","lofi","organic","warm","deep"}},
      },
    },
    { name="Underground", default_kw={"dirty","organic","punch","room","heavy","vintage"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","heavy","organic","dirty","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","dirty","punch"}},
        snare_alt={type="Snare Electronic", kw={"heavy","punch","organic","dirty"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","punch","dirty","room"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","acoustic","organic","bright","dirty"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","acoustic","bright","organic"}},
        crash    ={type="Crash",            kw={"organic","room","bright","dirty"}},
        ride     ={type="Ride",             kw={"acoustic","organic","bright","lofi"}},
        perc     ={type="Shakers",          kw={"organic","acoustic","bright","dirty"}},
        tom      ={type="Tom",              kw={"heavy","organic","punch","dirty","room"}},
      },
    },
    { name="Beatmaker", default_kw={"punch","organic","room","lofi","vintage","bright"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","organic","lofi","sub","vintage"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","punch","lofi","room"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","punch","organic","room","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","punch","snap","lofi"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","acoustic","bright","organic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","acoustic","bright","organic"}},
        crash    ={type="Crash",            kw={"organic","bright","room","lofi"}},
        ride     ={type="Ride",             kw={"acoustic","lofi","bright","organic"}},
        perc     ={type="Shakers",          kw={"organic","acoustic","lofi","bright"}},
        tom      ={type="Tom",              kw={"punch","organic","lofi","room","vintage"}},
      },
    },
    { name="Vintage Synth", default_kw={"synthetic","vintage","lofi","warm","organic","tape"},
      voices={
        kick     ={type="Kick Electronic",  kw={"synthetic","vintage","lofi","warm","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"synthetic","warm","organic","lofi"}},
        snare    ={type="Snare Electronic", kw={"synthetic","vintage","lofi","warm","machine"}},
        snare_alt={type="Snare Electronic", kw={"synthetic","warm","lofi","machine"}},
        clap     ={type="Claps & Snaps",    kw={"synthetic","lofi","warm","organic","machine"}},
        hh_c     ={type="Hihat Closed",     kw={"synthetic","lofi","warm","machine","vintage"}},
        hh_pedal ={type="Hihat Closed",     kw={"synthetic","lofi","machine"}},
        hh_o     ={type="HiHat Open",       kw={"synthetic","lofi","warm","machine"}},
        crash    ={type="Crash",            kw={"synthetic","lofi","warm","organic"}},
        ride     ={type="Ride",             kw={"synthetic","lofi","machine","vintage"}},
        perc     ={type="Perc Electronic",  kw={"synthetic","lofi","warm","machine","snap"}},
        tom      ={type="Tom",              kw={"synthetic","lofi","warm","organic","vintage"}},
      },
    },
    { name="Cozy", default_kw={"soft","warm","organic","lush","acoustic","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","warm","organic","deep","room"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","organic","warm","sub"}},
        snare    ={type="Snare Acoustic",   kw={"soft","warm","organic","bright","room"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","bright","organic","warm","acoustic"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","warm","acoustic","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","acoustic","bright","organic","warm"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","warm"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","organic","warm","bright"}},
        crash    ={type="Crash",            kw={"soft","organic","mallet","warm","room"}},
        ride     ={type="Ride",             kw={"soft","acoustic","warm","bright"}},
        perc     ={type="Shakers",          kw={"organic","soft","warm","acoustic","lush"}},
        tom      ={type="Tom",              kw={"soft","warm","organic","room","deep"}},
      },
    },
    { name="Night Lo-Fi", default_kw={"dark","organic","soft","warm","room","vintage"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","dark","organic","sub","warm"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","organic","dark","room"}},
        snare    ={type="Snare Acoustic",   kw={"soft","dark","organic","room","warm"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","organic","dark","warm","room"}},
        clap     ={type="Claps & Snaps",    kw={"soft","dark","organic","warm","room"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","dark","acoustic","organic","lofi"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","dark","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","dark","organic"}},
        crash    ={type="Crash",            kw={"soft","dark","organic","room","mallet"}},
        ride     ={type="Ride",             kw={"soft","acoustic","dark","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","dark","acoustic"}},
        tom      ={type="Tom",              kw={"soft","dark","organic","warm","room"}},
      },
    },

-- ═══ POP & DISCO +9 (anchor: tom kw bright,punch,organic,room,lush → }}, -- Rap)

    { name="Electro Pop", default_kw={"bright","synthetic","machine","wide","snap","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","synthetic","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","punch","wide","machine"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","wide","synthetic","punch"}},
        snare_alt={type="Snare Electronic", kw={"bright","wide","snap","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","synthetic","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","wide","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","machine"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","machine"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","machine"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","machine"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","synthetic","wide","machine"}},
        tom      ={type="Tom",              kw={"bright","wide","punch","synthetic","machine"}},
      },
    },
    { name="Indie Pop", default_kw={"organic","bright","room","acoustic","wide","lush"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","bright","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","bright","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","wide","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","wide","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","room","wide","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","room","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","wide","room"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","room","acoustic"}},
        ride     ={type="Ride",             kw={"bright","acoustic","organic","wide"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide","lush"}},
        tom      ={type="Tom",              kw={"organic","bright","room","wide","punch"}},
      },
    },
    { name="Cosmic Disco", default_kw={"lush","bright","disco","wide","organic","gold"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","disco","wide","lush"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","bright","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","wide","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","wide","organic","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","lush","wide","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","gold","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","lush","gold"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","wide","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lush","wide"}},
        tom      ={type="Tom",              kw={"bright","wide","organic","lush","punch"}},
      },
    },
    { name="Power Pop", default_kw={"bright","punch","wide","room","organic","hard"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","bright","room","heavy","organic"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","hard","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","room","organic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","wide","organic","room","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","punch","organic","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","room","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","wide"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","room","acoustic"}},
        ride     ={type="Ride",             kw={"bright","acoustic","organic","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide"}},
        tom      ={type="Tom",              kw={"punch","bright","room","organic","wide"}},
      },
    },
    { name="Soul Pop", default_kw={"organic","warm","bright","room","lush","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","warm","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","warm","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","warm","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","warm","organic","room","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","warm","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","warm","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","warm","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","warm","gold"}},
        crash    ={type="Crash",            kw={"bright","organic","room","warm","lush"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","warm"}},
        perc     ={type="Shakers",          kw={"organic","bright","warm","acoustic","lush"}},
        tom      ={type="Tom",              kw={"organic","warm","room","punch","bright"}},
      },
    },
    { name="K-Pop", default_kw={"bright","wide","synthetic","machine","punch","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","wide","punch","machine"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","wide","punch","synthetic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","snap","wide","room","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","wide","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","machine","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","synthetic","room"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","wide","synthetic"}},
        tom      ={type="Tom",              kw={"bright","wide","punch","organic","synthetic"}},
      },
    },
    { name="Bossa Pop", default_kw={"organic","bright","acoustic","warm","soft","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","organic","room","warm","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","organic","warm","sub"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","organic","room","warm"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","warm","organic","bright","room"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","bright","warm","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","acoustic","organic","warm"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","warm"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","organic","warm","bright"}},
        crash    ={type="Crash",            kw={"soft","organic","warm","bright","mallet"}},
        ride     ={type="Ride",             kw={"soft","bright","acoustic","warm"}},
        perc     ={type="Shakers",          kw={"organic","soft","warm","acoustic","bright"}},
        tom      ={type="Tom",              kw={"soft","organic","warm","room","wide"}},
      },
    },
    { name="Ambient Pop", default_kw={"soft","lush","wide","organic","bright","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","lush","organic","sub","wide"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","organic","room","deep"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","room","organic","wide"}},
        snare_alt={type="Snare Electronic", kw={"soft","layered","organic","lush"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","bright","wide","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","acoustic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","acoustic","wide","organic"}},
        crash    ={type="Crash",            kw={"soft","wide","organic","mallet","lush"}},
        ride     ={type="Ride",             kw={"soft","bright","acoustic","wide"}},
        perc     ={type="Shakers",          kw={"organic","soft","wide","lush","acoustic"}},
        tom      ={type="Tom",              kw={"soft","wide","organic","lush","room"}},
      },
    },
    { name="Hip Hop Pop", default_kw={"punch","bright","organic","synthetic","wide","sub"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","sub","organic","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","bright","organic"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","wide","organic","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","snap","organic","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","wide","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","organic","wide","room","synthetic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","organic","wide"}},
        perc     ={type="Shakers",          kw={"organic","bright","wide","acoustic"}},
        tom      ={type="Tom",              kw={"punch","bright","organic","wide","sub"}},
      },
    },
