-- JAZZ NEW VARIANTS (insert before closing }}, of Jazz section)
    { name="Hard Bop", default_kw={"punch","bright","organic","room","snap","gold"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","bright","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","bright","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"snap","bright","punch","room","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","snap","punch","flam","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","tight","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","room","acoustic","snap"}},
        tom      ={type="Tom",              kw={"punch","bright","organic","room","acoustic"}},
      },
    },
    { name="Dixieland", default_kw={"vintage","wide","organic","bright","room","acoustic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"wide","room","organic","deep","vintage"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","organic","wide","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","room","organic","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","flam","organic","room"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","wide","acoustic","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","vintage","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","vintage"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","vintage"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","room","vintage"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","wide","vintage"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","wide","acoustic","vintage"}},
        tom      ={type="Tom",              kw={"wide","organic","room","bright","vintage"}},
      },
    },
    { name="Big Band", default_kw={"wide","bright","punch","room","organic","gold"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","wide","room","organic","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","punch","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","punch","room","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","flam","punch","room"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","organic","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","room"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","room","organic"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","wide","room"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","wide","room","acoustic"}},
        tom      ={type="Tom",              kw={"wide","punch","organic","room","bright"}},
      },
    },
    { name="Post-Bop", default_kw={"bright","organic","creative","room","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","bright","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","bright","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","organic","room","creative"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","flam","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","creative","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","creative"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","creative","organic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","creative","room"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","organic","room"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","creative","acoustic","room"}},
        tom      ={type="Tom",              kw={"punch","organic","bright","creative","room"}},
      },
    },
    { name="Electric Miles", default_kw={"dark","heavy","layered","organic","synthetic","deep"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","organic","room","deep","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","dark","sub","layered","organic"}},
        snare    ={type="Snare Acoustic",   kw={"organic","room","heavy","bright","creative"}},
        snare_alt={type="Snare Electronic", kw={"heavy","layered","dark","synthetic","creative"}},
        clap     ={type="Claps & Snaps",    kw={"organic","heavy","dark","creative","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","metallic","organic","synthetic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","metallic","organic","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"dark","metallic","heavy","organic","synthetic"}},
        crash    ={type="Crash",            kw={"dark","heavy","metallic","organic","noise"}},
        ride     ={type="Ride",             kw={"dark","metallic","organic","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"dark","noise","heavy","synthetic","creative"}},
        tom      ={type="Tom",              kw={"heavy","dark","organic","layered","deep"}},
      },
    },
    { name="Smooth Jazz", default_kw={"soft","lush","bright","wide","organic","warm"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","room","organic","bright","lush"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","sub","organic","bright","lush"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","lush","room","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","soft","lush","room","wide"}},
        clap     ={type="Claps & Snaps",    kw={"soft","bright","lush","organic","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","gold","bright","acoustic","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","gold","bright","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","gold","bright","lush","wide"}},
        crash    ={type="Crash",            kw={"soft","bright","wide","acoustic","lush"}},
        ride     ={type="Ride",             kw={"soft","gold","bright","lush","acoustic"}},
        perc     ={type="Shakers",          kw={"soft","organic","bright","lush","wide"}},
        tom      ={type="Tom",              kw={"soft","lush","organic","bright","wide"}},
      },
    },
    { name="Avant-Garde", default_kw={"noise","creative","dark","heavy","organic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","room","organic","noise","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","heavy","dark","creative","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","noise","creative","organic","room"}},
        snare_alt={type="Snare Acoustic",   kw={"creative","noise","bright","organic","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"noise","creative","organic","dark","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","creative","dark","metallic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","creative","dark","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"noise","creative","dark","heavy","metallic"}},
        crash    ={type="Crash",            kw={"noise","creative","dark","heavy","organic"}},
        ride     ={type="Ride",             kw={"noise","creative","metallic","dark","organic"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","dark","heavy"}},
        tom      ={type="Tom",              kw={"heavy","noise","creative","dark","organic"}},
      },
    },
    { name="Second Line", default_kw={"wide","punch","bright","organic","snap","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","wide","room","organic","bright"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","punch","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","snap","wide","punch","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"snap","bright","wide","flam","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","organic","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","wide","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","wide","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","wide","organic","gold"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","wide","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","wide","snap","acoustic"}},
        tom      ={type="Tom",              kw={"wide","punch","bright","organic","room"}},
      },
    },
    { name="Gospel Jazz", default_kw={"heavy","wide","punch","bright","organic","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","punch","wide","room","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","wide","room","organic","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","punch","room","heavy"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","punch","heavy","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","punch","organic","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","heavy"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","heavy","acoustic"}},
        ride     ={type="Ride",             kw={"bright","gold","wide","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","wide","heavy","acoustic"}},
        tom      ={type="Tom",              kw={"heavy","wide","punch","organic","bright"}},
      },
    },
    { name="Chamber Jazz", default_kw={"soft","lush","acoustic","room","gold","organic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","room","organic","deep","bright"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","organic","room","deep"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","room","organic","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","soft","lush","organic","room"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","bright","acoustic","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","gold","bright","acoustic","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","gold","bright","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","gold","bright","lush","acoustic"}},
        crash    ={type="Crash",            kw={"soft","bright","acoustic","lush","room"}},
        ride     ={type="Ride",             kw={"soft","gold","bright","lush","acoustic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","soft","acoustic","lush","room"}},
        tom      ={type="Tom",              kw={"soft","lush","organic","acoustic","room"}},
      },
    },

-- REGGAE & DUB NEW VARIANTS (insert before closing }}, of Reggae & Dub section)
    { name="Nyahbinghi", default_kw={"organic","deep","acoustic","heavy","room","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","heavy","organic","room","wide"}},
        kick_alt ={type="Kick Acoustic",    kw={"deep","organic","heavy","room"}},
        snare    ={type="Snare Acoustic",   kw={"organic","wide","room","heavy","bright"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","organic","room","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","wide","room","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","organic","bright","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","organic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","organic","wide","heavy"}},
        crash    ={type="Crash",            kw={"acoustic","organic","wide","room","heavy"}},
        ride     ={type="Ride",             kw={"acoustic","bright","metallic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","heavy","deep","wide"}},
        tom      ={type="Tom",              kw={"deep","heavy","organic","wide","room"}},
      },
    },
    { name="One Drop", default_kw={"deep","organic","room","heavy","sub","soft"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","heavy","room","organic","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","sub","heavy","organic"}},
        snare    ={type="Snare Acoustic",   kw={"organic","room","soft","bright","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"room","soft","organic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"organic","soft","acoustic","room","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","soft","organic","bright"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","soft","organic"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","soft","organic","room"}},
        crash    ={type="Crash",            kw={"acoustic","organic","room","soft"}},
        ride     ={type="Ride",             kw={"acoustic","bright","organic","room"}},
        perc     ={type="Perc Acoustic",    kw={"organic","acoustic","room","soft","wide"}},
        tom      ={type="Tom",              kw={"deep","heavy","organic","room","sub"}},
      },
    },
    { name="Steppers", default_kw={"heavy","punch","organic","deep","wide","sub"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","punch","deep","organic","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","punch","sub","deep","organic"}},
        snare    ={type="Snare Acoustic",   kw={"organic","room","bright","wide","heavy"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","organic","room","bright","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"organic","heavy","wide","room","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","organic","bright","wide","heavy"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","organic","bright","heavy"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","organic","wide","heavy","bright"}},
        crash    ={type="Crash",            kw={"acoustic","organic","wide","room","heavy"}},
        ride     ={type="Ride",             kw={"acoustic","bright","organic","wide"}},
        perc     ={type="Perc Acoustic",    kw={"organic","heavy","wide","acoustic","room"}},
        tom      ={type="Tom",              kw={"heavy","deep","organic","wide","punch"}},
      },
    },
    { name="Dub Plate", default_kw={"dirty","lofi","organic","tape","vintage","heavy"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","heavy","dirty","organic","room"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","dirty","sub","heavy","tape"}},
        snare    ={type="Snare Acoustic",   kw={"lofi","tape","organic","room","dirty"}},
        snare_alt={type="Snare Acoustic",   kw={"tape","vinyl","dirty","organic","room"}},
        clap     ={type="Claps & Snaps",    kw={"lofi","tape","organic","dirty","vinyl"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","tape","acoustic","organic","dirty"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","tape","acoustic","dirty"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","tape","organic","dirty","vinyl"}},
        crash    ={type="Crash",            kw={"lofi","organic","tape","room","dirty"}},
        ride     ={type="Ride",             kw={"acoustic","tape","organic","lofi","dirty"}},
        perc     ={type="Perc Acoustic",    kw={"organic","lofi","tape","room","dirty"}},
        tom      ={type="Tom",              kw={"deep","heavy","dirty","organic","tape"}},
      },
    },
    { name="Bashment", default_kw={"bright","synthetic","snap","punch","sub","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"sub","punch","bright","wide","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"808","sub","punch","synthetic"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","punch","wide","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"snap","bright","wide","punch","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","snap","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","punch"}},
        crash    ={type="Crash",            kw={"bright","synthetic","wide","noise"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","synthetic","wide","punch"}},
        tom      ={type="Tom",              kw={"sub","heavy","punch","deep","wide"}},
      },
    },
    { name="Conscious Dub", default_kw={"deep","organic","soft","room","sub","vintage"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","soft","organic","room","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","sub","organic","soft"}},
        snare    ={type="Snare Acoustic",   kw={"soft","organic","room","bright","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"room","organic","soft","vintage","bright"}},
        clap     ={type="Claps & Snaps",    kw={"organic","soft","acoustic","room","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","soft","organic","bright","vintage"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","soft","organic","vintage"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","soft","organic","room","vintage"}},
        crash    ={type="Crash",            kw={"acoustic","organic","room","soft","vintage"}},
        ride     ={type="Ride",             kw={"acoustic","soft","organic","bright","vintage"}},
        perc     ={type="Perc Acoustic",    kw={"organic","soft","room","acoustic","vintage"}},
        tom      ={type="Tom",              kw={"deep","soft","organic","room","sub"}},
      },
    },
    { name="Deep Dub", default_kw={"dark","heavy","sub","noise","machine","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","sub","heavy","dark","noise"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","heavy","dark","machine","noise"}},
        snare    ={type="Snare Electronic", kw={"dark","heavy","noise","synthetic","organic"}},
        snare_alt={type="Snare Electronic", kw={"heavy","dark","noise","machine","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"dark","heavy","noise","organic","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","metallic","noise","synthetic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","metallic","noise","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"dark","heavy","noise","metallic","synthetic"}},
        crash    ={type="Crash",            kw={"dark","noise","heavy","metallic","synthetic"}},
        ride     ={type="Ride",             kw={"dark","metallic","noise","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"dark","noise","heavy","machine","synthetic"}},
        tom      ={type="Tom",              kw={"deep","sub","heavy","dark","noise"}},
      },
    },
    { name="Studio One", default_kw={"vintage","organic","bright","room","acoustic","warm"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"vintage","room","organic","bright","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","organic","vintage","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","vintage","room","organic","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"vintage","bright","organic","room","soft"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","vintage","acoustic","room"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","vintage","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","bright","vintage","gold"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","bright","vintage","organic","room"}},
        crash    ={type="Crash",            kw={"acoustic","bright","vintage","room","organic"}},
        ride     ={type="Ride",             kw={"acoustic","bright","gold","vintage","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","vintage","acoustic","room"}},
        tom      ={type="Tom",              kw={"organic","vintage","room","deep","bright"}},
      },
    },
    { name="Rub-a-Dub", default_kw={"bright","punch","organic","room","soft","acoustic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","bright","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","organic","bright","punch"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","soft","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","bright","organic","room","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","soft","acoustic","room"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","soft","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","bright","soft","gold"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","soft","bright","organic","room"}},
        crash    ={type="Crash",            kw={"acoustic","bright","organic","soft","room"}},
        ride     ={type="Ride",             kw={"acoustic","bright","gold","soft","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","soft","acoustic","wide"}},
        tom      ={type="Tom",              kw={"organic","room","bright","deep","soft"}},
      },
    },
    { name="Sound System", default_kw={"heavy","sub","wide","deep","machine","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"sub","heavy","deep","wide","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","heavy","machine","dark","wide"}},
        snare    ={type="Snare Electronic", kw={"heavy","wide","synthetic","machine","bright"}},
        snare_alt={type="Snare Electronic", kw={"wide","heavy","synthetic","bright","noise"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","wide","synthetic","bright","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","metallic","machine","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","metallic","machine"}},
        hh_o     ={type="HiHat Open",       kw={"synthetic","heavy","wide","machine","metallic"}},
        crash    ={type="Crash",            kw={"heavy","wide","synthetic","noise","metallic"}},
        ride     ={type="Ride",             kw={"metallic","synthetic","wide","machine"}},
        perc     ={type="Perc Electronic",  kw={"heavy","sub","wide","synthetic","machine"}},
        tom      ={type="Tom",              kw={"sub","deep","heavy","wide","organic"}},
      },
    },
    { name="Jungle Riddim", default_kw={"heavy","wide","punch","snap","noise","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","punch","sub","wide","noise"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","heavy","wide","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","snap","punch","wide","heavy"}},
        snare_alt={type="Snare Electronic", kw={"snap","heavy","punch","noise","bright"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","heavy","wide","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","tight","organic","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","tight","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","heavy","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","heavy","wide","noise","organic"}},
        ride     ={type="Ride",             kw={"bright","metallic","wide","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","heavy","wide","bright","snap"}},
        tom      ={type="Tom",              kw={"heavy","wide","punch","organic","deep"}},
      },
    },
