-- DRUM & BASS NEW VARIANTS (8 — insert before closing }}, of Drum & Bass section)
-- Anchor: after Soulful DnB tom line, before `  }},`

    { name="Sambass", default_kw={"organic","bright","punch","room","wide","metallic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","sub","organic","bright","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","snap","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","punch","organic","room"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","snap","room","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","metallic"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","metallic","wide","room"}},
        tom      ={type="Tom",              kw={"organic","punch","bright","room","wide"}},
      },
    },
    { name="Ragga DnB", default_kw={"heavy","sub","punch","organic","room","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","sub","deep","punch","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"heavy","punch","room","organic","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","snap","punch"}},
        snare_alt={type="Snare Electronic", kw={"heavy","noise","punch","organic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"organic","snap","bright","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","bright","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","bright","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","heavy"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","heavy"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide"}},
        tom      ={type="Tom",              kw={"heavy","sub","organic","deep","wide"}},
      },
    },
    { name="Coldstep", default_kw={"dark","synthetic","soft","sub","metallic","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"dark","sub","soft","synthetic","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"dark","soft","sub","layered"}},
        snare    ={type="Snare Electronic", kw={"dark","soft","synthetic","wide","layered"}},
        snare_alt={type="Snare Electronic", kw={"dark","synthetic","soft","wide"}},
        clap     ={type="Claps & Snaps",    kw={"dark","soft","synthetic","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","metallic","tight","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","metallic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"dark","metallic","synthetic","wide"}},
        crash    ={type="Crash",            kw={"dark","metallic","synthetic","wide"}},
        ride     ={type="Ride",             kw={"dark","metallic","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"dark","synthetic","metallic","soft"}},
        tom      ={type="Tom",              kw={"dark","sub","soft","wide","synthetic"}},
      },
    },
    { name="Crossbreed", default_kw={"hard","heavy","noise","metallic","dark","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","heavy","sub","noise","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","noise","dark"}},
        snare    ={type="Snare Electronic", kw={"hard","noise","metallic","heavy","punch"}},
        snare_alt={type="Snare Electronic", kw={"hard","noise","heavy","metallic"}},
        clap     ={type="Claps & Snaps",    kw={"hard","noise","heavy","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","metallic","hard","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","metallic","hard"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","heavy","hard","noise"}},
        crash    ={type="Crash",            kw={"noise","metallic","hard","heavy","dark"}},
        ride     ={type="Ride",             kw={"metallic","noise","hard","dark"}},
        perc     ={type="Perc Electronic",  kw={"noise","hard","metallic","punch"}},
        tom      ={type="Tom",              kw={"hard","heavy","noise","deep","punch"}},
      },
    },
    { name="Drumfunk", default_kw={"organic","punch","bright","room","snap","vintage"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","organic","sub","tight"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","snap","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","snap","punch","room","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","punch","organic","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","tight","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","tight","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","metallic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","vintage"}},
        tom      ={type="Tom",              kw={"punch","organic","bright","room","wide"}},
      },
    },
    { name="Jazz-Step", default_kw={"bright","gold","organic","room","acoustic","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","organic","sub","soft"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","soft"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","gold","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","gold","soft"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","room","soft"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","gold"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","gold","lush"}},
        tom      ={type="Tom",              kw={"bright","organic","room","soft","lush"}},
      },
    },
    { name="Autonomic", default_kw={"deep","sub","soft","organic","dark","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","sub","soft","organic","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","sub","dark","layered","soft"}},
        snare    ={type="Snare Electronic", kw={"heavy","wide","soft","dark","layered"}},
        snare_alt={type="Snare Acoustic",   kw={"soft","room","organic","dark","wide"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","dark","wide","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","dark","synthetic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","dark","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","dark","synthetic","wide"}},
        crash    ={type="Crash",            kw={"soft","dark","organic","mallet","wide"}},
        ride     ={type="Ride",             kw={"soft","dark","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","dark","wide"}},
        tom      ={type="Tom",              kw={"deep","sub","soft","dark","wide"}},
      },
    },
    { name="Clownstep", default_kw={"bright","punch","synthetic","machine","creative","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","machine","synthetic","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","snap","machine"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","punch","machine","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","machine","creative"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","punch","machine","creative"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","machine","snap"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","machine","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","machine","creative"}},
        crash    ={type="Crash",            kw={"bright","synthetic","creative","machine"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine","creative"}},
        perc     ={type="Perc Glitch",      kw={"blip","creative","bright","snap"}},
        tom      ={type="Tom",              kw={"punch","bright","machine","synthetic","wide"}},
      },
    },

-- ELECTRONICA NEW VARIANTS (9 — insert before closing }}, of Electronica section)
-- Anchor: after Hauntology tom line, before `  }},`

    { name="Breakcore", default_kw={"noise","heavy","creative","layered","dark","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"noise","heavy","layered","creative","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","heavy","dark","punch","dirty"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","snap","heavy","layered"}},
        snare_alt={type="Snare Electronic", kw={"noise","snap","creative","dark"}},
        clap     ={type="Claps & Snaps",    kw={"noise","snap","heavy","creative","dark"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","tight","synthetic","creative","dark"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","tight","synthetic","dark"}},
        hh_o     ={type="HiHat Open",       kw={"noise","heavy","synthetic","dark","creative"}},
        crash    ={type="Crash",            kw={"noise","creative","heavy","dark","synthetic"}},
        ride     ={type="Ride",             kw={"noise","creative","dark","synthetic"}},
        perc     ={type="Perc Glitch",      kw={"blip","creative","noise","dark"}},
        tom      ={type="Tom",              kw={"noise","heavy","creative","dark","deep"}},
      },
    },
    { name="Synthwave", default_kw={"machine","synthetic","bright","linn","707","vintage"},
      voices={
        kick     ={type="Kick Electronic",  kw={"machine","punch","synthetic","bright","808"}},
        kick_alt ={type="Kick Electronic",  kw={"machine","synthetic","deep","sub","707"}},
        snare    ={type="Snare Electronic", kw={"machine","bright","linn","synthetic","snap"}},
        snare_alt={type="Snare Electronic", kw={"machine","bright","synthetic","707","wide"}},
        clap     ={type="Claps & Snaps",    kw={"machine","bright","snap","synthetic","linn"}},
        hh_c     ={type="Hihat Closed",     kw={"machine","bright","synthetic","tight","707"}},
        hh_pedal ={type="Hihat Closed",     kw={"machine","bright","synthetic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"machine","bright","synthetic","wide"}},
        crash    ={type="Crash",            kw={"machine","bright","synthetic","wide"}},
        ride     ={type="Ride",             kw={"machine","bright","synthetic","metallic"}},
        perc     ={type="Perc Electronic",  kw={"machine","bright","snap","synthetic","blip"}},
        tom      ={type="Tom",              kw={"machine","synthetic","punch","bright","deep"}},
      },
    },
    { name="Witch House", default_kw={"dark","soft","heavy","tape","sub","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"dark","soft","heavy","sub","tape"}},
        kick_alt ={type="Kick Electronic",  kw={"dark","sub","heavy","synthetic","soft"}},
        snare    ={type="Snare Electronic", kw={"dark","soft","heavy","tape","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"dark","soft","synthetic","layered","tape"}},
        clap     ={type="Claps & Snaps",    kw={"dark","soft","tape","heavy","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","soft","synthetic","tight","tape"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","soft","synthetic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"dark","synthetic","heavy","soft","wide"}},
        crash    ={type="Crash",            kw={"dark","soft","noise","synthetic","tape"}},
        ride     ={type="Ride",             kw={"dark","synthetic","soft","metallic"}},
        perc     ={type="Perc Electronic",  kw={"dark","synthetic","soft","noise"}},
        tom      ={type="Tom",              kw={"dark","sub","soft","heavy","wide"}},
      },
    },
    { name="Industrial", default_kw={"hard","noise","metallic","heavy","dark","machine"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","heavy","sub","noise","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","noise","metallic","machine"}},
        snare    ={type="Snare Electronic", kw={"hard","noise","metallic","heavy","machine"}},
        snare_alt={type="Snare Electronic", kw={"hard","noise","heavy","metallic","dark"}},
        clap     ={type="Claps & Snaps",    kw={"hard","noise","heavy","metallic","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","hard","noise","tight","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","hard","noise","tight"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","heavy","hard","noise","machine"}},
        crash    ={type="Crash",            kw={"noise","metallic","hard","heavy","dark"}},
        ride     ={type="Ride",             kw={"metallic","noise","hard","machine"}},
        perc     ={type="Perc Electronic",  kw={"noise","metallic","hard","machine","snap"}},
        tom      ={type="Tom",              kw={"hard","heavy","noise","metallic","dark"}},
      },
    },
    { name="Noise", default_kw={"noise","heavy","creative","dark","layered","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"noise","heavy","dark","layered","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","heavy","creative","dark"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","heavy","dark","layered"}},
        snare_alt={type="Snare Electronic", kw={"noise","dark","heavy","creative"}},
        clap     ={type="Claps & Snaps",    kw={"noise","heavy","creative","dark"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","tight","dark","synthetic","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","tight","dark","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"noise","heavy","dark","synthetic"}},
        crash    ={type="Crash",            kw={"noise","dark","heavy","creative","synthetic"}},
        ride     ={type="Ride",             kw={"noise","dark","metallic","synthetic"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","dark","blip"}},
        tom      ={type="Tom",              kw={"noise","heavy","dark","creative","deep"}},
      },
    },
    { name="Microsound", default_kw={"soft","tight","synthetic","bright","organic","sub"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","tight","sub","synthetic","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","tight","sub","organic"}},
        snare    ={type="Snare Electronic", kw={"soft","tight","bright","synthetic","organic"}},
        snare_alt={type="Snare Electronic", kw={"soft","tight","synthetic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"soft","tight","bright","organic","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","tight","bright","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","tight","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","synthetic","tight"}},
        crash    ={type="Crash",            kw={"soft","bright","mallet","organic"}},
        ride     ={type="Ride",             kw={"soft","bright","synthetic","organic"}},
        perc     ={type="Perc Glitch",      kw={"blip","soft","creative","bright"}},
        tom      ={type="Tom",              kw={"soft","tight","sub","synthetic","organic"}},
      },
    },
    { name="Cyberpunk", default_kw={"hard","synthetic","machine","dark","sub","metallic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","sub","machine","synthetic","dark"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","machine","dark","noise"}},
        snare    ={type="Snare Electronic", kw={"hard","machine","synthetic","noise","dark"}},
        snare_alt={type="Snare Electronic", kw={"hard","noise","machine","metallic","dark"}},
        clap     ={type="Claps & Snaps",    kw={"hard","machine","noise","synthetic","dark"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","metallic","machine","dark","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","metallic","machine","dark"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","machine","dark","synthetic","heavy"}},
        crash    ={type="Crash",            kw={"noise","metallic","dark","machine","synthetic"}},
        ride     ={type="Ride",             kw={"metallic","machine","dark","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"machine","dark","noise","synthetic","metallic"}},
        tom      ={type="Tom",              kw={"hard","machine","synthetic","dark","deep"}},
      },
    },
    { name="Turntablism", default_kw={"lofi","vinyl","organic","punch","room","vintage"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","lofi","vinyl","organic","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","lofi","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","snap","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"room","organic","punch","snap","lofi"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","organic","punch","lofi"}},
        hh_c     ={type="Hihat Closed",     kw={"vinyl","lofi","tape","metallic","bright"}},
        hh_pedal ={type="Hihat Closed",     kw={"vinyl","lofi","metallic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"vinyl","lofi","bright","metallic","organic"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","lofi","bright"}},
        ride     ={type="Ride",             kw={"acoustic","lofi","metallic","organic","vintage"}},
        perc     ={type="Foley",            kw={"organic","lofi","vintage","room"}},
        tom      ={type="Tom",              kw={"punch","organic","room","lofi","vintage"}},
      },
    },
    { name="Post-Digital", default_kw={"organic","creative","noise","room","dark","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"organic","creative","noise","sub","dark"}},
        kick_alt ={type="Kick Acoustic",    kw={"organic","room","creative","dark","heavy"}},
        snare    ={type="Snare Electronic", kw={"organic","creative","noise","room","dark"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","room","dark","creative","noise"}},
        clap     ={type="Claps & Snaps",    kw={"organic","noise","creative","dark","room"}},
        hh_c     ={type="Hihat Closed",     kw={"organic","noise","creative","dark","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"organic","noise","creative","dark"}},
        hh_o     ={type="HiHat Open",       kw={"organic","noise","dark","creative","wide"}},
        crash    ={type="Crash",            kw={"organic","noise","creative","dark","room"}},
        ride     ={type="Ride",             kw={"organic","noise","dark","creative","metallic"}},
        perc     ={type="Perc Glitch",      kw={"blip","creative","noise","organic"}},
        tom      ={type="Tom",              kw={"organic","dark","noise","creative","room"}},
      },
    },
