-- RAP NEW VARIANTS (8) — insert after West Coast, before }},
    { name="Jazz Rap", default_kw={"organic","bright","room","gold","punch","vintage"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","bright","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","flam","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"room","bright","flam","organic","snap"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","gold","acoustic","bright","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","gold","acoustic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"soft","gold","acoustic","bright","room"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","soft"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","soft"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","room","soft"}},
        tom      ={type="Tom",              kw={"room","organic","bright","acoustic","soft"}},
      },
    },
    { name="Horrorcore", default_kw={"dark","heavy","noise","lofi","dirty"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","dark","sub","noise","lofi"}},
        kick_alt ={type="Kick Electronic",  kw={"dark","heavy","sub","dirty"}},
        snare    ={type="Snare Electronic", kw={"dark","heavy","noise","lofi","dirty"}},
        snare_alt={type="Snare Electronic", kw={"heavy","noise","dark","dirty","lofi"}},
        clap     ={type="Claps & Snaps",    kw={"dark","heavy","noise","dirty","lofi"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","noise","lofi","metallic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","noise","lofi","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"dark","noise","heavy","lofi","metallic"}},
        crash    ={type="Crash",            kw={"dark","noise","heavy","lofi","organic"}},
        ride     ={type="Ride",             kw={"dark","metallic","noise","lofi"}},
        perc     ={type="Perc Glitch",      kw={"noise","dark","creative","heavy"}},
        tom      ={type="Tom",              kw={"heavy","dark","sub","noise","deep"}},
      },
    },
    { name="Crunk", default_kw={"heavy","snap","punch","hard","synthetic","808"},
      voices={
        kick     ={type="Kick Electronic",  kw={"808","heavy","punch","sub","hard"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","808","sub","hard"}},
        snare    ={type="Snare Electronic", kw={"heavy","snap","punch","hard","808"}},
        snare_alt={type="Snare Electronic", kw={"snap","heavy","punch","hard","noise"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","snap","punch","hard","808"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","snap","noise","heavy"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","snap","noise"}},
        hh_o     ={type="HiHat Open",       kw={"heavy","synthetic","noise","snap"}},
        crash    ={type="Crash",            kw={"heavy","synthetic","noise","808","hard"}},
        ride     ={type="Ride",             kw={"synthetic","heavy","noise","808"}},
        perc     ={type="Perc Electronic",  kw={"snap","heavy","808","hard","noise"}},
        tom      ={type="Tom",              kw={"heavy","808","sub","deep","hard"}},
      },
    },
    { name="Hyphy", default_kw={"punch","bright","snap","synthetic","machine","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","hard"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","sub","snap"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","punch","wide","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"snap","bright","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","punch","wide","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","synthetic","snap","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","synthetic","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","tight"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","hard","snap"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","wide","synthetic","hard"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","sub","deep"}},
      },
    },
    { name="Midwest", default_kw={"organic","room","punch","lofi","vintage","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","deep","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"room","bright","snap","organic","lofi"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","snap","room"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","room","organic","lofi"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","bright","room","lofi"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","bright","room","organic","lofi"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","bright","lofi"}},
        ride     ={type="Ride",             kw={"acoustic","bright","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lofi","room"}},
        tom      ={type="Tom",              kw={"room","organic","punch","bright","lofi"}},
      },
    },
    { name="Detroit Rap", default_kw={"lofi","heavy","dark","synthetic","punch","dirty"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","punch","dark","lofi","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","dark","sub","dirty"}},
        snare    ={type="Snare Electronic", kw={"heavy","punch","noise","lofi","dirty"}},
        snare_alt={type="Snare Acoustic",   kw={"lofi","tape","organic","room","dirty"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","lofi","dirty","snap","dark"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","tape","metallic","dark","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","tape","metallic","dark"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","tape","heavy","dark","metallic"}},
        crash    ={type="Crash",            kw={"lofi","heavy","dark","organic","noise"}},
        ride     ={type="Ride",             kw={"lofi","metallic","dark","tape"}},
        perc     ={type="Perc Electronic",  kw={"dark","noise","lofi","punch","heavy"}},
        tom      ={type="Tom",              kw={"heavy","dark","lofi","sub","deep"}},
      },
    },
    { name="Grime", default_kw={"synthetic","dark","heavy","punch","tight","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","tight","sub","dark","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","tight","dark","noise"}},
        snare    ={type="Snare Electronic", kw={"heavy","punch","tight","dark","noise"}},
        snare_alt={type="Snare Electronic", kw={"tight","noise","punch","dark","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","snap","tight","dark","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","dark","noise","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","dark","noise"}},
        hh_o     ={type="HiHat Open",       kw={"synthetic","dark","noise","heavy","tight"}},
        crash    ={type="Crash",            kw={"synthetic","dark","noise","heavy"}},
        ride     ={type="Ride",             kw={"synthetic","dark","noise","tight"}},
        perc     ={type="Perc Electronic",  kw={"tight","noise","dark","snap","punch"}},
        tom      ={type="Tom",              kw={"heavy","dark","punch","sub","tight"}},
      },
    },
    { name="Instrumental Hip Hop", default_kw={"organic","room","soft","bright","vintage","lush"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","room","organic","punch","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","soft","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","soft","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"room","soft","organic","bright","snap"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","soft","room","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","acoustic","bright","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","bright","gold"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","bright","organic","room"}},
        crash    ={type="Crash",            kw={"soft","acoustic","room","organic","bright"}},
        ride     ={type="Ride",             kw={"soft","gold","acoustic","bright","room"}},
        perc     ={type="Shakers",          kw={"organic","soft","bright","acoustic","room"}},
        tom      ={type="Tom",              kw={"soft","room","organic","bright","acoustic"}},
      },
    },

-- ACOUSTIC NEW VARIANTS (10) — insert after Marching, before }},
    { name="Big Band", default_kw={"bright","wide","room","gold","punch","organic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","wide","room","punch","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","room","organic","punch"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","room","organic","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","room","flam","punch"}},
        clap     ={type="Claps & Snaps",    kw={"organic","wide","bright","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","room"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","room","organic"}},
        ride     ={type="Ride",             kw={"bright","gold","wide","acoustic","room"}},
        perc     ={type="Perc Acoustic",    kw={"organic","wide","bright","room","acoustic"}},
        tom      ={type="Tom",              kw={"wide","room","organic","bright","punch"}},
      },
    },
    { name="Cajon Kit", default_kw={"organic","room","acoustic","deep","punch","warm"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","organic","room","punch","soft"}},
        kick_alt ={type="Kick Acoustic",    kw={"organic","room","deep","soft"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","snap","soft"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","room","bright","soft","snap"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","bright","snap","room"}},
        hh_c     ={type="Hihat Closed",     kw={"acoustic","bright","organic","tight","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"acoustic","bright","organic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"acoustic","bright","organic","room","soft"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","soft","bright"}},
        ride     ={type="Ride",             kw={"acoustic","bright","organic","room"}},
        perc     ={type="Perc Acoustic",    kw={"organic","room","acoustic","soft","deep"}},
        tom      ={type="Tom",              kw={"deep","organic","room","acoustic","punch"}},
      },
    },
    { name="Samba", default_kw={"bright","organic","acoustic","wide","metallic","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","wide","organic","deep","room"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","organic","punch","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","organic","metallic","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","metallic","organic","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","wide","snap","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","organic","metallic"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","wide","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","wide","metallic","acoustic"}},
        tom      ={type="Tom",              kw={"wide","organic","punch","bright","room"}},
      },
    },
    { name="Steel Drum Kit", default_kw={"metallic","bright","mallet","organic","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","organic","room","punch","soft"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","organic","sub"}},
        snare    ={type="Snare Acoustic",   kw={"metallic","bright","organic","wide","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","metallic","organic","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","metallic","mallet","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","metallic","mallet","acoustic","wide"}},
        perc     ={type="Perc Acoustic",    kw={"metallic","mallet","bright","organic","wide"}},
        tom      ={type="Tom",              kw={"metallic","bright","mallet","organic","wide"}},
      },
    },
    { name="Taiko", default_kw={"heavy","wide","deep","punch","organic","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","wide","deep","punch","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","heavy","organic","deep"}},
        snare    ={type="Snare Acoustic",   kw={"heavy","wide","punch","organic","bright"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","heavy","organic","punch","flam"}},
        clap     ={type="Claps & Snaps",    kw={"organic","wide","punch","heavy","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","wide","heavy","acoustic","organic"}},
        ride     ={type="Ride",             kw={"bright","wide","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","wide","heavy","deep","djembe"}},
        tom      ={type="Tom",              kw={"heavy","wide","deep","organic","punch"}},
      },
    },
    { name="Hand Pan", default_kw={"metallic","mallet","bright","organic","soft","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","organic","deep","room","mallet"}},
        kick_alt ={type="Kick Acoustic",    kw={"organic","soft","room","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","soft","metallic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","soft","metallic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"organic","soft","acoustic","bright","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","soft","organic","acoustic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","soft","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","organic","soft","wide"}},
        crash    ={type="Crash",            kw={"bright","metallic","mallet","organic","soft"}},
        ride     ={type="Ride",             kw={"bright","metallic","mallet","organic","soft"}},
        perc     ={type="Perc Acoustic",    kw={"metallic","mallet","bright","organic","soft"}},
        tom      ={type="Tom",              kw={"metallic","mallet","soft","organic","bright"}},
      },
    },
    { name="Orchestra Perc", default_kw={"wide","bright","mallet","room","organic","lush"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","wide","room","organic","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","room","organic","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","room","organic","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","room","flam","organic"}},
        clap     ={type="Claps & Snaps",    kw={"organic","wide","bright","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","wide","acoustic","metallic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","wide","acoustic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","wide","acoustic","organic","metallic"}},
        crash    ={type="Crash",            kw={"bright","wide","mallet","room","organic"}},
        ride     ={type="Ride",             kw={"bright","wide","mallet","metallic","acoustic"}},
        perc     ={type="Perc Acoustic",    kw={"mallet","bright","wide","organic","metallic"}},
        tom      ={type="Tom",              kw={"wide","room","organic","bright","mallet"}},
      },
    },
    { name="Post-Rock", default_kw={"heavy","wide","room","punch","organic","lush"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","wide","room","punch","deep"}},
        kick_alt ={type="Kick Acoustic",    kw={"wide","room","heavy","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","room","heavy","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","room","organic","flam"}},
        clap     ={type="Claps & Snaps",    kw={"wide","organic","bright","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","wide","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","wide","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","wide","acoustic","organic","room"}},
        crash    ={type="Crash",            kw={"bright","wide","acoustic","room","organic"}},
        ride     ={type="Ride",             kw={"bright","wide","acoustic","room","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","wide","room","bright","acoustic"}},
        tom      ={type="Tom",              kw={"heavy","wide","room","organic","punch"}},
      },
    },
    { name="Punk / Rock", default_kw={"punch","hard","wide","bright","heavy","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","heavy","room","wide","bright"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","wide","punch","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","wide","room","heavy"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","punch","room","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","punch","organic","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","wide","metallic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","wide","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","wide","acoustic","organic","metallic"}},
        crash    ={type="Crash",            kw={"bright","wide","heavy","acoustic","organic"}},
        ride     ={type="Ride",             kw={"bright","wide","acoustic","metallic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","wide","bright","room","acoustic"}},
        tom      ={type="Tom",              kw={"punch","wide","room","heavy","organic"}},
      },
    },
    { name="Electronic Acoustic", default_kw={"synthetic","bright","organic","punch","wide","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","organic","layered","bright","wide"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","layered","organic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","snap","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","layered","organic","wide","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","organic","wide","acoustic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","organic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","organic","wide","acoustic"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","layered","acoustic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","organic","acoustic"}},
        perc     ={type="Perc Electronic",  kw={"bright","synthetic","organic","wide","snap"}},
        tom      ={type="Tom",              kw={"punch","layered","organic","bright","wide"}},
      },
    },
