-- BREAKBEAT NEW VARIANTS (11, to bring total to 20)
    { name="Funky Breaks", default_kw={"funk","punch","bright","organic","snap","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","deep","funk"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","organic","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","snap","room","organic","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","punch","organic"}},
        clap     ={type="Claps & Snaps",    kw={"snap","organic","bright","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","funk"}},
        tom      ={type="Tom",              kw={"organic","punch","room","bright","deep"}},
      },
    },
    { name="Glitch Breaks", default_kw={"glitch","creative","noise","synthetic","bright"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","noise","synthetic","sub","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","synthetic","creative","punch"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","synthetic","bright","punch"}},
        snare_alt={type="Snare Electronic", kw={"noise","synthetic","creative","bright"}},
        clap     ={type="Claps & Snaps",    kw={"noise","snap","creative","synthetic","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","noise","synthetic","creative"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","noise","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"noise","synthetic","creative","heavy"}},
        crash    ={type="Crash",            kw={"noise","creative","synthetic","bright"}},
        ride     ={type="Ride",             kw={"noise","synthetic","creative"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","synthetic","bright"}},
        tom      ={type="Tom",              kw={"noise","heavy","synthetic","creative"}},
      },
    },
    { name="Lo-Fi Breaks", default_kw={"lofi","tape","vinyl","vintage","organic","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","lofi","room","organic","vintage"}},
        kick_alt ={type="Kick Electronic",  kw={"lofi","tape","punch","sub","dirty"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","lofi","organic","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"lofi","tape","room","organic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"lofi","organic","tape","bright","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"lofi","acoustic","metallic","bright","tape"}},
        hh_pedal ={type="Hihat Closed",     kw={"lofi","acoustic","metallic","tape"}},
        hh_o     ={type="HiHat Open",       kw={"lofi","acoustic","bright","organic","tape"}},
        crash    ={type="Crash",            kw={"lofi","acoustic","organic","room","bright"}},
        ride     ={type="Ride",             kw={"lofi","acoustic","bright","metallic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","lofi","tape","bright","room"}},
        tom      ={type="Tom",              kw={"lofi","organic","room","punch","vintage"}},
      },
    },
    { name="Oldschool Breaks", default_kw={"vintage","warm","room","organic","tape","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","warm","vintage"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","deep","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","warm","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","punch","vintage","organic"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","room","warm","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","metallic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","metallic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","warm"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","warm"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","warm","room"}},
        tom      ={type="Tom",              kw={"organic","room","punch","warm","bright"}},
      },
    },
    { name="Tribal Breaks", default_kw={"djembe","organic","deep","punch","acoustic","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","punch","organic","room","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","sub","punch","organic"}},
        snare    ={type="Snare Acoustic",   kw={"organic","bright","room","punch","metallic"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","punch","room","bright"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","punch","bright","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","metallic"}},
        crash    ={type="Crash",            kw={"bright","organic","acoustic","metallic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","punch","room"}},
        tom      ={type="Tom",              kw={"deep","organic","punch","room","wide"}},
      },
    },
    { name="Cut & Paste", default_kw={"creative","layered","synthetic","noise","bright","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","layered","synthetic","sub","creative"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","layered","creative","punch"}},
        snare    ={type="Snare Electronic", kw={"layered","creative","bright","synthetic","punch"}},
        snare_alt={type="Snare Electronic", kw={"creative","noise","bright","layered"}},
        clap     ={type="Claps & Snaps",    kw={"snap","creative","layered","bright","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","creative","bright","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","creative","bright"}},
        hh_o     ={type="HiHat Open",       kw={"synthetic","creative","bright","noise"}},
        crash    ={type="Crash",            kw={"creative","noise","bright","synthetic"}},
        ride     ={type="Ride",             kw={"creative","synthetic","bright","noise"}},
        perc     ={type="Perc Glitch",      kw={"creative","noise","snap","bright","synthetic"}},
        tom      ={type="Tom",              kw={"layered","synthetic","punch","creative"}},
      },
    },
    { name="Abstract Beats", default_kw={"creative","dark","layered","noise","wide","deep"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","sub","dark","heavy","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"dark","noise","heavy","sub"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","dark","layered","heavy"}},
        snare_alt={type="Snare Electronic", kw={"dark","heavy","noise","creative"}},
        clap     ={type="Claps & Snaps",    kw={"noise","dark","creative","heavy","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","noise","tight","synthetic","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","noise","tight","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"dark","noise","synthetic","heavy"}},
        crash    ={type="Crash",            kw={"dark","noise","heavy","creative","metallic"}},
        ride     ={type="Ride",             kw={"dark","noise","metallic","creative"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","dark","heavy"}},
        tom      ={type="Tom",              kw={"deep","dark","heavy","wide","creative"}},
      },
    },
    { name="Future Beats", default_kw={"wide","bright","synthetic","layered","sub","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","wide","sub","bright","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"wide","synthetic","sub","punch"}},
        snare    ={type="Snare Electronic", kw={"bright","wide","layered","synthetic","punch"}},
        snare_alt={type="Snare Electronic", kw={"wide","bright","synthetic","layered"}},
        clap     ={type="Claps & Snaps",    kw={"snap","wide","bright","synthetic","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","synthetic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","layered"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","creative","layered"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","creative"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","synthetic","wide","blip"}},
        tom      ={type="Tom",              kw={"wide","sub","punch","synthetic","bright"}},
      },
    },
    { name="Rave Breaks", default_kw={"hard","bright","heavy","punch","synthetic","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","punch","bright","sub","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","sub","noise"}},
        snare    ={type="Snare Electronic", kw={"bright","hard","punch","snap","noise"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","hard","heavy","noise"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","hard","punch","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","hard","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","hard"}},
        hh_o     ={type="HiHat Open",       kw={"bright","heavy","synthetic","noise","hard"}},
        crash    ={type="Crash",            kw={"bright","noise","heavy","hard","synthetic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","noise","hard"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","hard","noise","punch"}},
        tom      ={type="Tom",              kw={"hard","heavy","punch","bright","noise"}},
      },
    },
    { name="DnB Breaks", default_kw={"punch","heavy","bright","tight","sub","fast"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","heavy","sub","tight","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","sub","punch","dark"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","snap","heavy","tight"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","snap","room","punch","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","punch","heavy","tight"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","metallic","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","tight","heavy"}},
        crash    ={type="Crash",            kw={"bright","heavy","metallic","organic"}},
        ride     ={type="Ride",             kw={"bright","metallic","tight","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"snap","bright","punch","tight","noise"}},
        tom      ={type="Tom",              kw={"heavy","punch","tight","bright","sub"}},
      },
    },
    { name="Halftime Breaks", default_kw={"heavy","deep","sub","wide","layered","dark"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","deep","sub","wide","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","sub","dark","layered"}},
        snare    ={type="Snare Electronic", kw={"heavy","wide","layered","punch","deep"}},
        snare_alt={type="Snare Electronic", kw={"heavy","dark","noise","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","snap","wide","punch","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","dark","synthetic","metallic","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","dark","synthetic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"dark","heavy","synthetic","noise","wide"}},
        crash    ={type="Crash",            kw={"heavy","dark","noise","wide","synthetic"}},
        ride     ={type="Ride",             kw={"dark","metallic","synthetic","noise"}},
        perc     ={type="Perc Electronic",  kw={"heavy","sub","noise","synthetic","dark"}},
        tom      ={type="Tom",              kw={"heavy","deep","sub","wide","dark"}},
      },
    },

-- AFROBEAT NEW VARIANTS (11, to bring total to 20)
    { name="Fela Style", default_kw={"organic","room","punch","deep","vintage","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","deep","room","organic","vintage"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","room","bright","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","room","bright","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","metallic","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","metallic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","metallic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","metallic"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic","room"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","balafon","room"}},
        tom      ={type="Tom",              kw={"organic","deep","room","punch","wide"}},
      },
    },
    { name="Tony Allen Style", default_kw={"organic","tight","bright","metallic","room","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","tight","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","bright","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","tight","metallic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","tight","room","punch"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","snap","tight","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","tight","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","tight"}},
        crash    ={type="Crash",            kw={"bright","metallic","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","tight","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","metallic","tight"}},
        tom      ={type="Tom",              kw={"organic","tight","bright","room","punch"}},
      },
    },
    { name="Afro Funk", default_kw={"funk","organic","punch","bright","room","deep"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","deep","room","funk"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","organic","bright","funk"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","snap","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","metallic","organic","funk"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","metallic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","metallic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","balafon","funk"}},
        tom      ={type="Tom",              kw={"organic","punch","deep","room","bright"}},
      },
    },
    { name="Afro Disco", default_kw={"disco","bright","organic","lush","wide","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","sub","wide","disco"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","bright","room","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","wide","organic","lush"}},
        snare_alt={type="Snare Electronic", kw={"bright","wide","punch","organic","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","organic","disco"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","organic","wide","acoustic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","gold","acoustic","wide"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide","lush"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","organic","room"}},
      },
    },
    { name="Afro Electronic", default_kw={"synthetic","bright","organic","punch","wide","djembe"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","sub","bright"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","synthetic","organic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","synthetic","organic","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","tight","organic","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","tight","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","organic","wide","metallic"}},
        crash    ={type="Crash",            kw={"bright","synthetic","organic","wide","room"}},
        ride     ={type="Ride",             kw={"bright","synthetic","metallic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","punch","balafon"}},
        tom      ={type="Tom",              kw={"organic","punch","bright","synthetic","wide"}},
      },
    },
    { name="Lagos Street", default_kw={"heavy","punch","bright","organic","wide","sub"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","heavy","sub","bright","wide"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","heavy"}},
        snare    ={type="Snare Electronic", kw={"punch","bright","heavy","organic","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","punch","organic","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","metallic","organic","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","metallic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","organic","metallic","wide","heavy"}},
        crash    ={type="Crash",            kw={"bright","organic","wide","heavy","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","organic","wide"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","punch","heavy"}},
        tom      ={type="Tom",              kw={"heavy","punch","organic","bright","wide"}},
      },
    },
    { name="Afro Punk", default_kw={"heavy","bright","organic","noise","punch","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","punch","sub","bright","noise"}},
        kick_alt ={type="Kick Acoustic",    kw={"heavy","punch","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","punch","heavy","organic"}},
        snare_alt={type="Snare Electronic", kw={"bright","heavy","punch","noise","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","heavy","punch","snap","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","heavy","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","heavy"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","heavy","acoustic","noise"}},
        crash    ={type="Crash",            kw={"bright","heavy","organic","noise","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","heavy","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","heavy","punch"}},
        tom      ={type="Tom",              kw={"heavy","organic","punch","bright","wide"}},
      },
    },
    { name="Afro Spiritual", default_kw={"deep","organic","warm","room","soft","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","organic","room","warm","soft"}},
        kick_alt ={type="Kick Acoustic",    kw={"deep","organic","room","heavy"}},
        snare    ={type="Snare Acoustic",   kw={"organic","room","soft","bright","warm"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","room","warm","bright","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","soft","bright","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","metallic","organic","soft"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","metallic","soft"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","soft"}},
        crash    ={type="Crash",            kw={"bright","organic","acoustic","room","soft"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic","soft"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","balafon","warm"}},
        tom      ={type="Tom",              kw={"deep","organic","warm","room","wide"}},
      },
    },
    { name="Naija Beats", default_kw={"punch","bright","sub","wide","synthetic","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","sub","bright","wide","lush"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","sub","organic"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","wide","lush","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","wide","lush","organic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","tight","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","tight","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","organic","lush"}},
        crash    ={type="Crash",            kw={"bright","organic","wide","lush","room"}},
        ride     ={type="Ride",             kw={"bright","organic","wide","synthetic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","punch","wide"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","sub","organic"}},
      },
    },
    { name="Afro Jazz", default_kw={"organic","bright","room","metallic","soft","acoustic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","organic","room","soft","bright"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","organic","room","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","soft","metallic"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","room","bright","soft","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","bright","soft","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","room"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","metallic"}},
        ride     ={type="Ride",             kw={"bright","metallic","gold","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","balafon","soft"}},
        tom      ={type="Tom",              kw={"organic","room","bright","soft","punch"}},
      },
    },
    { name="Highlife Electronic", default_kw={"bright","synthetic","organic","wide","vintage","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","bright","room","organic","vintage"}},
        snare    ={type="Snare Electronic", kw={"bright","wide","organic","synthetic","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","wide","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","wide","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","synthetic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","synthetic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","organic","wide","synthetic"}},
        crash    ={type="Crash",            kw={"bright","organic","wide","synthetic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","synthetic","organic","wide"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","balafon","punch","wide"}},
        tom      ={type="Tom",              kw={"organic","bright","wide","punch","room"}},
      },
    },
