-- FOOTWORK NEW VARIANTS (13) — insert before closing }}, of Footwork section
-- Existing: Chicago, Juke, Ghetto House, Battle, Teklife, Neo Juke, Bass Music

    { name="Juke House", default_kw={"punch","deep","lush","organic","sub","machine"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","deep","sub","organic","lush"}},
        kick_alt ={type="Kick Electronic",  kw={"808","deep","sub","punch"}},
        snare    ={type="Snare Electronic", kw={"punch","bright","organic","layered","wide"}},
        snare_alt={type="Snare Electronic", kw={"punch","soft","organic","lush"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","lush","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","organic","bright","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","organic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"bright","organic","synthetic","lush"}},
        crash    ={type="Crash",            kw={"bright","organic","lush","wide"}},
        ride     ={type="Ride",             kw={"bright","organic","synthetic","wide"}},
        perc     ={type="Perc Electronic",  kw={"blip","soft","organic","synthetic"}},
        tom      ={type="Tom",              kw={"deep","punch","organic","sub"}},
      },
    },
    { name="Floatin", default_kw={"soft","dark","sub","synthetic","layered","deep"},
      voices={
        kick     ={type="Kick Electronic",  kw={"sub","deep","soft","dark","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"808","sub","dark","deep"}},
        snare    ={type="Snare Electronic", kw={"soft","dark","layered","synthetic","wide"}},
        snare_alt={type="Snare Electronic", kw={"soft","synthetic","dark","layered"}},
        clap     ={type="Claps & Snaps",    kw={"soft","synthetic","dark","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","soft","synthetic","dark"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","soft","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","synthetic","dark","wide"}},
        crash    ={type="Crash",            kw={"soft","dark","synthetic","layered"}},
        ride     ={type="Ride",             kw={"soft","synthetic","dark"}},
        perc     ={type="Perc Electronic",  kw={"soft","blip","synthetic","dark"}},
        tom      ={type="Tom",              kw={"sub","deep","dark","soft"}},
      },
    },
    { name="Stepper", default_kw={"tight","machine","snap","synthetic","hard","dry"},
      voices={
        kick     ={type="Kick Electronic",  kw={"tight","punch","hard","synthetic","snap"}},
        kick_alt ={type="Kick Electronic",  kw={"tight","machine","hard","snap"}},
        snare    ={type="Snare Electronic", kw={"tight","snap","synthetic","hard","bright"}},
        snare_alt={type="Snare Electronic", kw={"tight","snap","hard","bright"}},
        clap     ={type="Claps & Snaps",    kw={"snap","tight","hard","synthetic","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","machine","bright"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","machine"}},
        hh_o     ={type="HiHat Open",       kw={"tight","synthetic","bright","machine"}},
        crash    ={type="Crash",            kw={"bright","synthetic","tight","hard"}},
        ride     ={type="Ride",             kw={"synthetic","tight","machine","bright"}},
        perc     ={type="Perc Electronic",  kw={"snap","tight","hard","machine"}},
        tom      ={type="Tom",              kw={"tight","punch","hard","deep"}},
      },
    },
    { name="Booty", default_kw={"808","heavy","sub","punch","bass","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"808","sub","heavy","punch","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"808","sub","heavy","bass"}},
        snare    ={type="Snare Electronic", kw={"808","heavy","snap","punch","wide"}},
        snare_alt={type="Snare Electronic", kw={"808","snap","heavy","punch"}},
        clap     ={type="Claps & Snaps",    kw={"808","snap","heavy","punch","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","808","synthetic","snap"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","808","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"808","synthetic","heavy","wide"}},
        crash    ={type="Crash",            kw={"808","heavy","synthetic","wide"}},
        ride     ={type="Ride",             kw={"808","synthetic","machine"}},
        perc     ={type="Perc Electronic",  kw={"808","snap","heavy","blip"}},
        tom      ={type="Tom",              kw={"808","sub","heavy","deep"}},
      },
    },
    { name="Bangs", default_kw={"punch","hard","bright","snap","heavy","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","hard","heavy","sub","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","hard","heavy","snap"}},
        snare    ={type="Snare Electronic", kw={"hard","punch","bright","snap","heavy"}},
        snare_alt={type="Snare Electronic", kw={"hard","punch","snap","noise","bright"}},
        clap     ={type="Claps & Snaps",    kw={"hard","snap","punch","bright","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","hard","snap","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","hard","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","hard","metallic","heavy"}},
        crash    ={type="Crash",            kw={"bright","hard","heavy","noise","metallic"}},
        ride     ={type="Ride",             kw={"bright","metallic","hard","noise"}},
        perc     ={type="Perc Electronic",  kw={"snap","hard","bright","punch","noise"}},
        tom      ={type="Tom",              kw={"punch","hard","heavy","bright"}},
      },
    },
    { name="UK Footwork", default_kw={"tight","sub","punch","bright","synthetic","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"sub","punch","tight","bright","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","tight","punch","snap"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","tight","snap","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"bright","tight","snap","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","tight","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","synthetic","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","tight","wide"}},
        crash    ={type="Crash",            kw={"bright","synthetic","wide","metallic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","metallic","wide"}},
        perc     ={type="Perc Electronic",  kw={"blip","bright","snap","tight","synthetic"}},
        tom      ={type="Tom",              kw={"sub","punch","tight","deep"}},
      },
    },
    { name="Tokyo Footwork", default_kw={"bright","tight","synthetic","clean","machine","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"tight","bright","punch","synthetic","clean"}},
        kick_alt ={type="Kick Electronic",  kw={"tight","bright","snap","machine"}},
        snare    ={type="Snare Electronic", kw={"bright","tight","snap","synthetic","clean"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","tight","machine"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","tight","synthetic","clean"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","synthetic","metallic","clean"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","synthetic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","tight","metallic"}},
        crash    ={type="Crash",            kw={"bright","synthetic","metallic","wide"}},
        ride     ={type="Ride",             kw={"bright","metallic","synthetic","tight"}},
        perc     ={type="Perc Electronic",  kw={"blip","bright","tight","synthetic","machine"}},
        tom      ={type="Tom",              kw={"tight","punch","bright","synthetic"}},
      },
    },
    { name="Future Footwork", default_kw={"layered","wide","bright","synthetic","creative","sub"},
      voices={
        kick     ={type="Kick Electronic",  kw={"layered","wide","sub","punch","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"layered","sub","synthetic","wide"}},
        snare    ={type="Snare Electronic", kw={"wide","bright","layered","synthetic","creative"}},
        snare_alt={type="Snare Electronic", kw={"bright","layered","wide","creative"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","layered","synthetic","creative"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","wide","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","creative"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","creative","layered"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","creative"}},
        perc     ={type="Perc Glitch",      kw={"creative","bright","synthetic","wide"}},
        tom      ={type="Tom",              kw={"wide","punch","layered","sub","bright"}},
      },
    },
    { name="Drillin", default_kw={"hard","heavy","dark","noise","punch","tight"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","heavy","punch","dark","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","dark","noise"}},
        snare    ={type="Snare Electronic", kw={"hard","heavy","noise","punch","tight"}},
        snare_alt={type="Snare Electronic", kw={"hard","noise","heavy","dark"}},
        clap     ={type="Claps & Snaps",    kw={"hard","heavy","noise","punch","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","hard","noise","metallic","dark"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","hard","noise","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"hard","noise","dark","heavy"}},
        crash    ={type="Crash",            kw={"noise","hard","heavy","dark","metallic"}},
        ride     ={type="Ride",             kw={"metallic","hard","noise","dark"}},
        perc     ={type="Perc Electronic",  kw={"noise","hard","punch","heavy","dark"}},
        tom      ={type="Tom",              kw={"hard","heavy","dark","punch"}},
      },
    },
    { name="Flexin", default_kw={"bright","snap","punch","wide","synthetic","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","snap"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","snap","layered"}},
        snare    ={type="Snare Electronic", kw={"bright","snap","punch","wide","layered"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","punch","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","punch","wide","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","snap","synthetic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","snap","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","snap"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","layered"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","layered"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","punch","synthetic","blip"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","snap"}},
      },
    },
    { name="Jersey Footwork", default_kw={"punch","tight","bright","snap","808","machine"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","tight","bright","sub","808"}},
        kick_alt ={type="Kick Electronic",  kw={"808","tight","punch","snap"}},
        snare    ={type="Snare Electronic", kw={"tight","snap","bright","punch","808"}},
        snare_alt={type="Snare Electronic", kw={"tight","bright","snap","machine"}},
        clap     ={type="Claps & Snaps",    kw={"snap","tight","bright","punch","808"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","808","synthetic","snap"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","808","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","808","synthetic","tight"}},
        crash    ={type="Crash",            kw={"bright","808","synthetic","wide"}},
        ride     ={type="Ride",             kw={"bright","808","synthetic","machine"}},
        perc     ={type="Perc Electronic",  kw={"snap","blip","bright","808","tight"}},
        tom      ={type="Tom",              kw={"punch","tight","808","deep"}},
      },
    },
    { name="Trap Footwork", default_kw={"808","snap","heavy","dark","sub","machine"},
      voices={
        kick     ={type="Kick Electronic",  kw={"808","sub","heavy","dark","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"808","heavy","sub","dark"}},
        snare    ={type="Snare Electronic", kw={"808","snap","heavy","punch","bright"}},
        snare_alt={type="Snare Electronic", kw={"808","heavy","snap","dark"}},
        clap     ={type="Claps & Snaps",    kw={"808","snap","heavy","punch","bright"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","808","synthetic","snap","dark"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","808","synthetic","snap"}},
        hh_o     ={type="HiHat Open",       kw={"808","synthetic","dark","heavy"}},
        crash    ={type="Crash",            kw={"808","dark","synthetic","heavy"}},
        ride     ={type="Ride",             kw={"808","dark","synthetic","machine"}},
        perc     ={type="Perc Electronic",  kw={"808","snap","heavy","blip","dark"}},
        tom      ={type="Tom",              kw={"808","sub","heavy","dark"}},
      },
    },
    { name="Prank", default_kw={"noise","creative","bright","snap","synthetic","glitch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","noise","synthetic","snap"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","punch","synthetic","creative"}},
        snare    ={type="Snare Electronic", kw={"noise","snap","bright","creative","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"noise","bright","creative","snap"}},
        clap     ={type="Claps & Snaps",    kw={"snap","noise","bright","creative","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","noise","synthetic","bright","creative"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","noise","synthetic","bright"}},
        hh_o     ={type="HiHat Open",       kw={"noise","synthetic","bright","creative"}},
        crash    ={type="Crash",            kw={"noise","bright","creative","synthetic"}},
        ride     ={type="Ride",             kw={"noise","synthetic","bright","creative"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","snap","bright","synthetic"}},
        tom      ={type="Tom",              kw={"noise","punch","bright","creative"}},
      },
    },

-- TRANCE NEW VARIANTS (9) — insert before closing }}, of Trance section
-- Existing: Uplifting, Tech, Dark Psy, Progressive, Melodic, Goa, Hi-NRG/Eurodance, Hard Trance, Acid Trance, Orchestral Trance, Tribal Trance

    { name="Full-On", default_kw={"punch","bright","heavy","layered","noise","wide"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","heavy","bright","sub","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","heavy","sub","noise"}},
        snare    ={type="Snare Electronic", kw={"bright","heavy","punch","layered","noise"}},
        snare_alt={type="Snare Electronic", kw={"heavy","noise","bright","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","punch","heavy","layered","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","tight","synthetic","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","tight","noise"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","heavy","noise"}},
        crash    ={type="Crash",            kw={"bright","heavy","noise","metallic","wide"}},
        ride     ={type="Ride",             kw={"bright","metallic","noise","wide"}},
        perc     ={type="Perc Electronic",  kw={"noise","bright","heavy","snap","metallic"}},
        tom      ={type="Tom",              kw={"heavy","punch","noise","wide","bright"}},
      },
    },
    { name="Deep Trance", default_kw={"deep","sub","dark","lush","layered","soft"},
      voices={
        kick     ={type="Kick Electronic",  kw={"sub","deep","dark","soft","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","deep","dark","lush"}},
        snare    ={type="Snare Electronic", kw={"soft","wide","layered","dark","lush"}},
        snare_alt={type="Snare Electronic", kw={"soft","layered","dark","wide"}},
        clap     ={type="Claps & Snaps",    kw={"soft","wide","layered","dark","organic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","dark","synthetic","tight","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","dark","synthetic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"soft","dark","synthetic","wide"}},
        crash    ={type="Crash",            kw={"soft","dark","wide","layered","lush"}},
        ride     ={type="Ride",             kw={"soft","dark","synthetic","wide"}},
        perc     ={type="Shakers",          kw={"soft","organic","dark","wide"}},
        tom      ={type="Tom",              kw={"sub","deep","dark","soft","wide"}},
      },
    },
    { name="Club Trance", default_kw={"punch","bright","wide","synthetic","snap","hard"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","hard"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","sub","tight"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","wide","snap","synthetic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","wide","room","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","punch","wide","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","metallic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","metallic"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","room","organic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","metallic"}},
        perc     ={type="Shakers",          kw={"bright","organic","wide","synthetic"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","sub"}},
      },
    },
    { name="Minimal Trance", default_kw={"tight","synthetic","bright","clean","soft","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"tight","punch","bright","sub","soft"}},
        kick_alt ={type="Kick Electronic",  kw={"tight","soft","bright","synthetic"}},
        snare    ={type="Snare Electronic", kw={"bright","tight","soft","synthetic","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","soft","organic"}},
        clap     ={type="Claps & Snaps",    kw={"soft","bright","organic","synthetic","tight"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","soft","synthetic","acoustic"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","soft","synthetic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","soft","synthetic","organic"}},
        crash    ={type="Crash",            kw={"bright","soft","organic","wide","acoustic"}},
        ride     ={type="Ride",             kw={"bright","soft","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"soft","organic","bright","acoustic"}},
        tom      ={type="Tom",              kw={"soft","bright","punch","organic"}},
      },
    },
    { name="Euro Trance", default_kw={"bright","wide","punch","synthetic","lush","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","lush"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","wide","synthetic"}},
        snare    ={type="Snare Electronic", kw={"bright","wide","punch","lush","synthetic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","wide","lush"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","lush","snap","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","wide","synthetic","tight","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","wide","synthetic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","wide","lush","organic","room"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","lush"}},
        perc     ={type="Shakers",          kw={"bright","organic","lush","wide"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","lush"}},
      },
    },
    { name="Morning Trance", default_kw={"bright","soft","lush","organic","wide","warm"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","soft"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","soft","organic","lush"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","wide","organic","soft"}},
        snare_alt={type="Snare Electronic", kw={"bright","soft","wide","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","soft","organic","wide","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","soft","organic","gold"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","soft","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","soft","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","room","soft"}},
        ride     ={type="Ride",             kw={"bright","acoustic","gold","organic","soft"}},
        perc     ={type="Shakers",          kw={"soft","organic","bright","acoustic","lush"}},
        tom      ={type="Tom",              kw={"bright","soft","organic","wide","lush"}},
      },
    },
    { name="Ibiza", default_kw={"bright","wide","lush","punch","organic","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","sub","organic"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","organic","lush"}},
        snare    ={type="Snare Electronic", kw={"bright","wide","punch","layered","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","wide","organic","lush"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","lush","organic","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","gold","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","wide","organic","lush"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","room","lush"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","wide","lush"}},
        perc     ={type="Shakers",          kw={"organic","bright","lush","acoustic","wide"}},
        tom      ={type="Tom",              kw={"punch","bright","wide","organic","lush"}},
      },
    },
    { name="Trance Core", default_kw={"hard","punch","noise","heavy","bright","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"hard","punch","heavy","sub","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","punch","noise"}},
        snare    ={type="Snare Electronic", kw={"hard","punch","bright","noise","heavy"}},
        snare_alt={type="Snare Electronic", kw={"hard","noise","punch","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"hard","snap","punch","bright","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","hard","bright","metallic","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","hard","bright","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"hard","bright","metallic","heavy"}},
        crash    ={type="Crash",            kw={"hard","bright","heavy","noise","metallic"}},
        ride     ={type="Ride",             kw={"hard","metallic","bright","noise"}},
        perc     ={type="Perc Electronic",  kw={"hard","snap","bright","noise","punch"}},
        tom      ={type="Tom",              kw={"hard","heavy","punch","bright"}},
      },
    },
    { name="Neuro Trance", default_kw={"layered","dark","synthetic","heavy","creative","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","dark","layered","sub","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","dark","sub","noise"}},
        snare    ={type="Snare Electronic", kw={"dark","heavy","layered","noise","creative"}},
        snare_alt={type="Snare Electronic", kw={"dark","layered","heavy","noise"}},
        clap     ={type="Claps & Snaps",    kw={"dark","heavy","noise","synthetic","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","tight","synthetic","noise","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","tight","synthetic","noise"}},
        hh_o     ={type="HiHat Open",       kw={"dark","synthetic","heavy","noise"}},
        crash    ={type="Crash",            kw={"dark","heavy","noise","metallic","synthetic"}},
        ride     ={type="Ride",             kw={"dark","metallic","noise","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"dark","noise","heavy","creative","synthetic"}},
        tom      ={type="Tom",              kw={"heavy","dark","sub","layered","noise"}},
      },
    },
