-- WORLD NEW VARIANTS (8 new → total 20)
    { name="Cumbia", default_kw={"bright","organic","punch","acoustic","metallic","wide"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","deep","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","organic","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","wide","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","snap","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","wide"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","acoustic","metallic","punch"}},
        tom      ={type="Tom",              kw={"organic","bright","punch","room","wide"}},
      },
    },
    { name="Bollywood", default_kw={"bright","organic","metallic","punch","wide","acoustic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","deep","organic","room","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","sub","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","punch","room","metallic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","metallic","organic","room","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","metallic","wide","acoustic","organic"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","wide","organic"}},
        perc     ={type="Perc Acoustic",    kw={"metallic","organic","bright","acoustic","punch"}},
        tom      ={type="Tom",              kw={"bright","organic","punch","room","wide"}},
      },
    },
    { name="Ethiopian", default_kw={"organic","bright","metallic","acoustic","deep","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","punch","organic","room","heavy"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","organic","deep","punch"}},
        snare    ={type="Snare Acoustic",   kw={"organic","bright","room","metallic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","wide","flam"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","room","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","room"}},
        crash    ={type="Crash",            kw={"bright","metallic","acoustic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","metallic","acoustic","room"}},
        tom      ={type="Tom",              kw={"deep","organic","room","bright","punch"}},
      },
    },
    { name="Gnawa", default_kw={"deep","metallic","organic","acoustic","heavy","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"deep","heavy","organic","room","punch"}},
        kick_alt ={type="Kick Acoustic",    kw={"heavy","deep","organic","room"}},
        snare    ={type="Snare Acoustic",   kw={"heavy","organic","room","metallic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","heavy","room","metallic"}},
        clap     ={type="Claps & Snaps",    kw={"organic","acoustic","heavy","room","metallic"}},
        hh_c     ={type="Hihat Closed",     kw={"metallic","heavy","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"metallic","heavy","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","heavy","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"metallic","organic","heavy","acoustic","room"}},
        ride     ={type="Ride",             kw={"metallic","heavy","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"metallic","organic","heavy","acoustic","deep"}},
        tom      ={type="Tom",              kw={"deep","heavy","organic","room","metallic"}},
      },
    },
    { name="Mbalax", default_kw={"bright","organic","punch","metallic","acoustic","fast"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","bright","organic","room","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","organic","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","organic","room","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","snap","room","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","acoustic","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","tight","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","tight","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","metallic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"djembe","organic","bright","punch","acoustic"}},
        tom      ={type="Tom",              kw={"punch","organic","bright","room","wide"}},
      },
    },
    { name="Balkanic", default_kw={"bright","metallic","organic","acoustic","wide","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","heavy","organic","room","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","heavy","organic","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","wide","metallic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","wide","organic","room","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","wide","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","wide","organic"}},
        crash    ={type="Crash",            kw={"bright","metallic","wide","acoustic","organic"}},
        ride     ={type="Ride",             kw={"bright","metallic","wide","acoustic","organic"}},
        perc     ={type="Perc Acoustic",    kw={"metallic","bright","organic","acoustic","wide"}},
        tom      ={type="Tom",              kw={"bright","organic","punch","wide","room"}},
      },
    },
    { name="Andean", default_kw={"organic","acoustic","bright","wide","soft","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"room","organic","deep","soft","bright"}},
        kick_alt ={type="Kick Acoustic",    kw={"organic","deep","room","soft"}},
        snare    ={type="Snare Acoustic",   kw={"bright","organic","room","wide","soft"}},
        snare_alt={type="Snare Acoustic",   kw={"organic","bright","room","wide"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","soft","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","metallic","soft"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic","soft"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","wide","soft"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","wide","room"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","organic","wide"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","acoustic","wide","metallic"}},
        tom      ={type="Tom",              kw={"organic","bright","room","soft","wide"}},
      },
    },
    { name="Taiko", default_kw={"heavy","deep","wide","organic","punch","acoustic"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","deep","wide","punch","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"heavy","deep","organic","room","wide"}},
        snare    ={type="Snare Acoustic",   kw={"heavy","bright","wide","organic","room"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","heavy","organic","room","punch"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","organic","acoustic","wide","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","wide","acoustic","organic"}},
        crash    ={type="Crash",            kw={"bright","wide","metallic","organic","room"}},
        ride     ={type="Ride",             kw={"bright","metallic","wide","acoustic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","heavy","wide","acoustic","punch"}},
        tom      ={type="Tom",              kw={"heavy","deep","wide","organic","punch"}},
      },
    },

-- FUNK NEW VARIANTS (10 new → total 20)
    { name="Rare Groove", default_kw={"vintage","organic","room","punch","lofi","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","vintage","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","organic","sub","vintage","lofi"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","vintage","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"room","organic","bright","flam","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","room","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","vintage"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","vintage"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","vintage"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","vintage"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","vintage"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","vintage"}},
        tom      ={type="Tom",              kw={"punch","room","organic","vintage","bright"}},
      },
    },
    { name="Jazz Funk", default_kw={"organic","bright","room","gold","punch","lush"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","deep","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","sub","organic","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","flam"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","organic","room","flam","snap"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","room","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","room","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","room","organic"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","room"}},
        tom      ={type="Tom",              kw={"room","organic","bright","punch","acoustic"}},
      },
    },
    { name="Fusion Funk", default_kw={"layered","organic","bright","punch","synthetic","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","layered","sub","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","layered","organic","room"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","layered","organic","snap","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","synthetic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","room"}},
        tom      ={type="Tom",              kw={"punch","bright","organic","room","layered"}},
      },
    },
    { name="Disco Funk", default_kw={"disco","bright","lush","organic","gold","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","lush","sub","disco"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","bright","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        snare_alt={type="Snare Electronic", kw={"bright","snap","lush","layered","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","lush","disco"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","lush"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","acoustic","organic","room","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","lush"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lush"}},
        tom      ={type="Tom",              kw={"bright","punch","lush","organic","room"}},
      },
    },
    { name="Gospel Funk", default_kw={"heavy","wide","organic","room","bright","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","punch","room","organic","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","punch","sub","organic","bright"}},
        snare    ={type="Snare Acoustic",   kw={"bright","wide","room","organic","heavy"}},
        snare_alt={type="Snare Acoustic",   kw={"wide","bright","organic","room","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","organic","room","heavy"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","wide","organic"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","wide"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide"}},
        tom      ={type="Tom",              kw={"heavy","wide","organic","room","bright"}},
      },
    },
    { name="Drum Break", default_kw={"punch","snap","vintage","room","lofi","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","vintage","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","snap","organic","lofi","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","punch","room","snap","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"snap","bright","punch","room","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","organic","punch","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","gold","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","gold","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","gold","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","room"}},
        tom      ={type="Tom",              kw={"punch","room","organic","bright","vintage"}},
      },
    },
    { name="Trap Funk", default_kw={"808","snap","punch","bright","synthetic","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"808","punch","sub","bright","snap"}},
        kick_alt ={type="Kick Electronic",  kw={"808","heavy","sub","punch"}},
        snare    ={type="Snare Electronic", kw={"snap","bright","punch","808","synthetic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","snap","organic","punch"}},
        clap     ={type="Claps & Snaps",    kw={"snap","bright","808","punch","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","bright","808","synthetic","snap"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","bright","808","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","808","synthetic","wide"}},
        crash    ={type="Crash",            kw={"bright","808","synthetic","wide"}},
        ride     ={type="Ride",             kw={"bright","synthetic","808","wide"}},
        perc     ={type="Perc Electronic",  kw={"snap","808","bright","blip","punch"}},
        tom      ={type="Tom",              kw={"808","punch","deep","bright","sub"}},
      },
    },
    { name="Synth Funk", default_kw={"synthetic","707","linn","bright","machine","snap"},
      voices={
        kick     ={type="Kick Electronic",  kw={"707","linn","punch","bright","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"707","machine","bright","snap"}},
        snare    ={type="Snare Electronic", kw={"linn","707","snap","bright","machine"}},
        snare_alt={type="Snare Electronic", kw={"707","snap","bright","synthetic","machine"}},
        clap     ={type="Claps & Snaps",    kw={"linn","707","snap","bright","synthetic"}},
        hh_c     ={type="Hihat Closed",     kw={"707","linn","bright","machine","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"707","linn","machine","tight"}},
        hh_o     ={type="HiHat Open",       kw={"707","linn","bright","synthetic","wide"}},
        crash    ={type="Crash",            kw={"bright","synthetic","machine","wide"}},
        ride     ={type="Ride",             kw={"bright","machine","synthetic","wide"}},
        perc     ={type="Perc Electronic",  kw={"linn","707","snap","bright","blip"}},
        tom      ={type="Tom",              kw={"707","linn","machine","punch","bright"}},
      },
    },
    { name="Slow Jam", default_kw={"soft","lush","organic","warm","room","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","room","organic","deep","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","sub","organic","lush","warm"}},
        snare    ={type="Snare Acoustic",   kw={"soft","room","organic","bright","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","soft","organic","room","flam"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","bright","acoustic","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","gold","acoustic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","bright","gold","acoustic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","gold","acoustic","wide"}},
        crash    ={type="Crash",            kw={"soft","bright","acoustic","room","organic"}},
        ride     ={type="Ride",             kw={"soft","bright","gold","acoustic","room"}},
        perc     ={type="Shakers",          kw={"soft","organic","bright","acoustic","lush"}},
        tom      ={type="Tom",              kw={"soft","room","organic","lush","bright"}},
      },
    },
    { name="Contemporary R&B", default_kw={"layered","bright","punch","synthetic","organic","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","layered","sub","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","lush","organic","sub","bright"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","layered","synthetic","snap"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","lush"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","layered","synthetic","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","organic","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","lush"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","organic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","room","lush"}},
        ride     ={type="Ride",             kw={"bright","synthetic","organic","wide","lush"}},
        perc     ={type="Shakers",          kw={"organic","bright","synthetic","lush","wide"}},
        tom      ={type="Tom",              kw={"punch","bright","layered","organic","lush"}},
      },
    },
