-- LO-FI NEW VARIANTS (10 new → 20 total)
-- Insert before closing }}, of Lo-Fi section

    { name="Bedroom Pop", default_kw={"soft","lofi","bright","organic","warm","tape"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","lofi","organic","warm","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","room","organic","lofi"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","room","organic","lofi"}},
        snare_alt={type="Snare Acoustic",   kw={"room","soft","bright","organic","flam"}},
        clap     ={type="Claps & Snaps",    kw={"soft","bright","organic","lofi","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","acoustic","organic","lofi"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","bright","acoustic","lofi"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"soft","acoustic","room","organic","mallet"}},
        ride     ={type="Ride",             kw={"soft","bright","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","bright","acoustic"}},
        tom      ={type="Tom",              kw={"soft","room","organic","lofi","bright"}},
      },
    },
    { name="Indie Lo-Fi", default_kw={"lofi","organic","room","dirty","tape","bright"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","lofi","dirty"}},
        kick_alt ={type="Kick Electronic",  kw={"lofi","dirty","punch","sub","organic"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","lofi","dirty"}},
        snare_alt={type="Snare Acoustic",   kw={"room","bright","lofi","organic","punch"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","lofi","room","dirty"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","lofi","metallic","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","lofi","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","lofi","organic","room"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","lofi","bright"}},
        ride     ={type="Ride",             kw={"bright","acoustic","lofi","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lofi"}},
        tom      ={type="Tom",              kw={"room","organic","lofi","punch","dirty"}},
      },
    },
    { name="Lo-Fi Rock", default_kw={"lofi","heavy","room","organic","dirty","tape"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"heavy","punch","room","organic","lofi"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","lofi","punch","sub","dirty"}},
        snare    ={type="Snare Acoustic",   kw={"heavy","room","bright","organic","lofi"}},
        snare_alt={type="Snare Acoustic",   kw={"room","heavy","bright","lofi","punch"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","organic","bright","lofi","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","metallic","acoustic","lofi","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","metallic","acoustic","lofi"}},
        hh_o     ={type="HiHat Open",       kw={"bright","metallic","acoustic","heavy","lofi"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","heavy","lofi"}},
        ride     ={type="Ride",             kw={"bright","acoustic","metallic","lofi","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lofi"}},
        tom      ={type="Tom",              kw={"heavy","room","organic","lofi","punch"}},
      },
    },
    { name="Rainy Day", default_kw={"soft","tape","lofi","organic","room","vinyl"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","lofi","tape","sub","organic"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","room","lofi","tape","organic"}},
        snare    ={type="Snare Acoustic",   kw={"soft","room","lofi","tape","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"room","soft","lofi","organic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","lofi","tape","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","acoustic","lofi","tape","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","acoustic","lofi","tape"}},
        hh_o     ={type="HiHat Open",       kw={"soft","acoustic","lofi","tape","organic"}},
        crash    ={type="Crash",            kw={"soft","acoustic","room","lofi","organic"}},
        ride     ={type="Ride",             kw={"soft","acoustic","lofi","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","acoustic","lofi"}},
        tom      ={type="Tom",              kw={"soft","room","lofi","tape","organic"}},
      },
    },
    { name="Study Beats", default_kw={"soft","bright","organic","lush","lofi","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"soft","sub","organic","lush","lofi"}},
        kick_alt ={type="Kick Acoustic",    kw={"soft","room","organic","lofi","deep"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","room","organic","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"room","soft","bright","organic","flam"}},
        clap     ={type="Claps & Snaps",    kw={"soft","bright","organic","acoustic","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","acoustic","gold","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","bright","acoustic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","acoustic","organic","lush"}},
        crash    ={type="Crash",            kw={"soft","acoustic","room","organic","mallet"}},
        ride     ={type="Ride",             kw={"soft","bright","gold","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","soft","bright","acoustic","lush"}},
        tom      ={type="Tom",              kw={"soft","room","organic","lush","bright"}},
      },
    },
    { name="City Pop Lo-Fi", default_kw={"bright","lush","organic","vintage","soft","disco"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","lush","organic","vintage"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","vintage"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","lush","vintage"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","flam","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","lush","acoustic","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","lush"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","lush"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","lush"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","organic","lush"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lush","vintage"}},
        tom      ={type="Tom",              kw={"bright","organic","room","lush","vintage"}},
      },
    },
    { name="VHS Aesthetic", default_kw={"tape","vinyl","lofi","dark","dirty","noise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"tape","lofi","dirty","heavy","noise"}},
        kick_alt ={type="Kick Electronic",  kw={"lofi","dark","tape","dirty","sub"}},
        snare    ={type="Snare Electronic", kw={"tape","lofi","dirty","noise","dark"}},
        snare_alt={type="Snare Acoustic",   kw={"tape","lofi","room","dirty","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"tape","lofi","dirty","organic","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"tape","lofi","metallic","noise","dark"}},
        hh_pedal ={type="Hihat Closed",     kw={"tape","lofi","metallic","noise"}},
        hh_o     ={type="HiHat Open",       kw={"tape","lofi","organic","noise","dark"}},
        crash    ={type="Crash",            kw={"tape","lofi","organic","noise","dark"}},
        ride     ={type="Ride",             kw={"tape","lofi","metallic","noise","dark"}},
        perc     ={type="Perc Glitch",      kw={"noise","lofi","dark","dirty","tape"}},
        tom      ={type="Tom",              kw={"tape","lofi","dirty","organic","dark"}},
      },
    },
    { name="Lo-Fi Country", default_kw={"tape","organic","room","vintage","acoustic","warm"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","vintage","lofi"}},
        kick_alt ={type="Kick Acoustic",    kw={"room","organic","soft","vintage","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","vintage","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"room","bright","organic","flam","vintage"}},
        clap     ={type="Claps & Snaps",    kw={"organic","bright","acoustic","room","vintage"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic","vintage"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","gold","vintage"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","vintage"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","vintage","bright"}},
        ride     ={type="Ride",             kw={"bright","acoustic","gold","room","vintage"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","vintage","room"}},
        tom      ={type="Tom",              kw={"room","organic","vintage","acoustic","lofi"}},
      },
    },
    { name="Lo-Fi Funk", default_kw={"lofi","punch","organic","warm","vintage","funk"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","lofi","organic","warm","vintage"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","lofi","sub","organic","dirty"}},
        snare    ={type="Snare Acoustic",   kw={"snap","punch","lofi","room","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"room","punch","lofi","organic","bright"}},
        clap     ={type="Claps & Snaps",    kw={"snap","organic","lofi","bright","punch"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","lofi","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","lofi"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","lofi","organic"}},
        crash    ={type="Crash",            kw={"acoustic","room","organic","lofi","bright"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","lofi","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lofi","snap"}},
        tom      ={type="Tom",              kw={"room","punch","organic","lofi","warm"}},
      },
    },
    { name="Broken Beat", default_kw={"organic","bright","synthetic","room","layered","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","organic","bright","layered","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","deep"}},
        snare    ={type="Snare Electronic", kw={"bright","organic","layered","punch","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","punch","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","layered","snap","room"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","gold","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic","gold"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","organic"}},
        perc     ={type="Perc Electronic",  kw={"bright","organic","synthetic","snap","blip"}},
        tom      ={type="Tom",              kw={"organic","bright","punch","room","layered"}},
      },
    },

-- POP & DISCO NEW VARIANTS (9 new → 20 total)
-- Insert before closing }}, of Pop & Disco section

    { name="Bubblegum Pop", default_kw={"bright","snap","wide","synthetic","lush","pop"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","wide","synthetic","snap"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","wide","punch","lush"}},
        snare    ={type="Snare Electronic", kw={"bright","wide","snap","synthetic","lush"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","wide","snap","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","snap","synthetic","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","wide","snap"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","snap"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","wide","synthetic","lush","room"}},
        ride     ={type="Ride",             kw={"bright","synthetic","wide","lush"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","blip","wide","synthetic"}},
        tom      ={type="Tom",              kw={"bright","wide","punch","synthetic","lush"}},
      },
    },
    { name="Arena Pop", default_kw={"wide","heavy","bright","lush","layered","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"heavy","punch","wide","sub","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","wide","punch","bright"}},
        snare    ={type="Snare Electronic", kw={"heavy","wide","bright","layered","punch"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","wide","heavy","organic"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","wide","bright","layered","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","wide","synthetic","tight","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","wide","synthetic","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","wide","synthetic","heavy"}},
        crash    ={type="Crash",            kw={"bright","wide","heavy","organic","room"}},
        ride     ={type="Ride",             kw={"bright","wide","acoustic","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","wide","lush"}},
        tom      ={type="Tom",              kw={"heavy","wide","bright","punch","layered"}},
      },
    },
    { name="Cosmic Disco", default_kw={"bright","lush","wide","disco","synthetic","gold"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","disco","lush","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","wide","organic","punch","lush"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","wide","organic","lush"}},
        snare_alt={type="Snare Electronic", kw={"bright","wide","synthetic","lush","layered"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","organic","lush","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide","lush"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","wide","organic","lush","room"}},
        ride     ={type="Ride",             kw={"bright","gold","wide","acoustic","lush"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide","lush"}},
        tom      ={type="Tom",              kw={"bright","wide","punch","lush","organic"}},
      },
    },
    { name="Soul Disco", default_kw={"bright","organic","warm","disco","lush","punch"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"punch","room","organic","warm","deep"}},
        kick_alt ={type="Kick Electronic",  kw={"punch","bright","organic","lush","sub"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","warm","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"room","bright","organic","flam","wide"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","acoustic","room","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","room"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","lush"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","lush"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","organic","room"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lush","warm"}},
        tom      ={type="Tom",              kw={"bright","punch","organic","room","warm"}},
      },
    },
    { name="Freestyle", default_kw={"bright","synthetic","punch","snap","wide","machine"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","synthetic","wide","machine"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","synthetic","punch","snap","sub"}},
        snare    ={type="Snare Electronic", kw={"bright","synthetic","snap","wide","machine"}},
        snare_alt={type="Snare Electronic", kw={"snap","bright","wide","synthetic","punch"}},
        clap     ={type="Claps & Snaps",    kw={"bright","snap","synthetic","wide","machine"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","tight","machine","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","tight","machine"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","machine","wide"}},
        crash    ={type="Crash",            kw={"bright","synthetic","machine","wide"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine","wide"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","blip","machine","synthetic"}},
        tom      ={type="Tom",              kw={"bright","synthetic","machine","punch","wide"}},
      },
    },
    { name="Electro Pop", default_kw={"synthetic","bright","machine","snap","wide","layered"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","synthetic","bright","machine","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"bright","synthetic","machine","punch","layered"}},
        snare    ={type="Snare Electronic", kw={"bright","synthetic","machine","snap","layered"}},
        snare_alt={type="Snare Electronic", kw={"snap","bright","synthetic","wide","layered"}},
        clap     ={type="Claps & Snaps",    kw={"bright","synthetic","machine","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","machine","tight","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","machine","tight"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","machine","wide"}},
        crash    ={type="Crash",            kw={"bright","synthetic","machine","wide","creative"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine","wide"}},
        perc     ={type="Perc Electronic",  kw={"bright","synthetic","snap","blip","machine"}},
        tom      ={type="Tom",              kw={"bright","synthetic","machine","wide","layered"}},
      },
    },
    { name="New Wave", default_kw={"synthetic","dark","machine","organic","bright","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","synthetic","machine","dark","bright"}},
        kick_alt ={type="Kick Electronic",  kw={"machine","synthetic","dark","punch","sub"}},
        snare    ={type="Snare Electronic", kw={"bright","synthetic","machine","room","organic"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","wide","snap"}},
        clap     ={type="Claps & Snaps",    kw={"bright","synthetic","machine","organic","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","synthetic","machine","organic","tight"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","synthetic","machine","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","machine","organic"}},
        crash    ={type="Crash",            kw={"bright","synthetic","organic","room","machine"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine","organic"}},
        perc     ={type="Perc Electronic",  kw={"synthetic","bright","machine","snap","blip"}},
        tom      ={type="Tom",              kw={"synthetic","machine","bright","organic","room"}},
      },
    },
    { name="Post-Disco", default_kw={"bright","organic","punch","wide","synthetic","lush"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","organic","wide","lush"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","wide"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","wide","organic","snap"}},
        snare_alt={type="Snare Electronic", kw={"bright","wide","organic","snap","layered"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","wide","snap","lush"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","gold","acoustic","organic","wide"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","gold","acoustic","wide"}},
        hh_o     ={type="HiHat Open",       kw={"bright","gold","acoustic","organic","wide"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","organic","wide"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","wide","lush"}},
        tom      ={type="Tom",              kw={"bright","punch","organic","wide","room"}},
      },
    },
    { name="Tropical Pop", default_kw={"bright","organic","wide","lush","acoustic","synthetic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","bright","organic","wide","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","bright","wide"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","wide","snap"}},
        snare_alt={type="Snare Electronic", kw={"bright","wide","snap","synthetic","organic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","wide","organic","snap","acoustic"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","organic","wide","metallic"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","organic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","wide","lush"}},
        crash    ={type="Crash",            kw={"bright","acoustic","room","organic","wide"}},
        ride     ={type="Ride",             kw={"bright","acoustic","organic","wide","metallic"}},
        perc     ={type="Perc Acoustic",    kw={"organic","bright","acoustic","wide","metallic"}},
        tom      ={type="Tom",              kw={"bright","organic","wide","punch","room"}},
      },
    },
