-- TECHNO NEW VARIANTS (insert after "Bleep / UK Rave", before }}, closing Techno)
-- Anchor: tom ={type="Tom", kw={"808","machine","bright","deep","synthetic"}},
--         followed by }, }, }},

    { name="Drone", default_kw={"dark","sub","deep","layered","heavy","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","sub","heavy","dark","layered"}},
        kick_alt ={type="Kick Electronic",  kw={"sub","organic","dark","layered","deep"}},
        snare    ={type="Snare Electronic", kw={"dark","layered","organic","heavy","noise"}},
        snare_alt={type="Snare Electronic", kw={"layered","dark","heavy","noise"}},
        clap     ={type="Claps & Snaps",    kw={"dark","heavy","organic","layered","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","metallic","soft","synthetic"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","metallic","soft"}},
        hh_o     ={type="HiHat Open",       kw={"dark","metallic","heavy","organic"}},
        crash    ={type="Crash",            kw={"dark","organic","mallet","heavy","noise"}},
        ride     ={type="Ride",             kw={"dark","metallic","organic","soft"}},
        perc     ={type="Perc Electronic",  kw={"dark","noise","metallic","synthetic"}},
        tom      ={type="Tom",              kw={"deep","sub","dark","heavy","layered"}},
      },
    },
    { name="Berlin School", default_kw={"dark","tight","synthetic","metallic","machine","precise"},
      voices={
        kick     ={type="Kick Electronic",  kw={"tight","dark","sub","machine","synthetic"}},
        kick_alt ={type="Kick Electronic",  kw={"dark","sub","tight","heavy"}},
        snare    ={type="Snare Electronic", kw={"tight","dark","metallic","machine","synthetic"}},
        snare_alt={type="Snare Electronic", kw={"dark","tight","metallic","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"dark","tight","synthetic","machine","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","metallic","synthetic","dark","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","metallic","machine","dark"}},
        hh_o     ={type="HiHat Open",       kw={"metallic","synthetic","dark","heavy"}},
        crash    ={type="Crash",            kw={"metallic","dark","synthetic","noise"}},
        ride     ={type="Ride",             kw={"metallic","dark","machine","synthetic"}},
        perc     ={type="Perc Electronic",  kw={"metallic","synthetic","dark","tight","machine"}},
        tom      ={type="Tom",              kw={"dark","tight","synthetic","heavy","machine"}},
      },
    },
    { name="Modular", default_kw={"noise","creative","synthetic","dark","metallic","heavy"},
      voices={
        kick     ={type="Kick Electronic",  kw={"synthetic","noise","deep","creative","heavy"}},
        kick_alt ={type="Kick Electronic",  kw={"noise","creative","synthetic","dark"}},
        snare    ={type="Snare Electronic", kw={"noise","creative","synthetic","metallic","dark"}},
        snare_alt={type="Snare Electronic", kw={"creative","noise","metallic","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"noise","creative","synthetic","dark","snap"}},
        hh_c     ={type="Hihat Closed",     kw={"noise","synthetic","metallic","creative"}},
        hh_pedal ={type="Hihat Closed",     kw={"noise","synthetic","metallic"}},
        hh_o     ={type="HiHat Open",       kw={"noise","synthetic","heavy","metallic"}},
        crash    ={type="Crash",            kw={"noise","creative","metallic","synthetic","dark"}},
        ride     ={type="Ride",             kw={"noise","metallic","synthetic","creative"}},
        perc     ={type="Perc Glitch",      kw={"noise","creative","synthetic","metallic"}},
        tom      ={type="Tom",              kw={"synthetic","noise","creative","deep","dark"}},
      },
    },
    { name="Oldskool Rave", default_kw={"punch","bright","hard","synthetic","wide","heavy"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","hard","wide","bright","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"hard","heavy","punch","sub"}},
        snare    ={type="Snare Electronic", kw={"bright","punch","hard","snap","wide"}},
        snare_alt={type="Snare Electronic", kw={"hard","bright","snap","heavy"}},
        clap     ={type="Claps & Snaps",    kw={"bright","hard","punch","snap","wide"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","tight","synthetic","hard","machine"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","tight","synthetic","hard"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","hard","heavy"}},
        crash    ={type="Crash",            kw={"bright","hard","synthetic","wide","heavy"}},
        ride     ={type="Ride",             kw={"bright","synthetic","hard","metallic"}},
        perc     ={type="Perc Electronic",  kw={"bright","snap","hard","synthetic","wide"}},
        tom      ={type="Tom",              kw={"heavy","punch","hard","bright","wide"}},
      },
    },

-- HOUSE NEW VARIANTS (insert after "Future House", before }}, closing House)
-- Anchor: tom ={type="Tom", kw={"bright","wide","punch","synthetic","sub"}},
--         followed by }, }, }},

    { name="Acid House", default_kw={"synthetic","tight","noise","bright","machine","organic"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","punch","organic","bright","sub"}},
        kick_alt ={type="Kick Electronic",  kw={"deep","punch","sub","organic"}},
        snare    ={type="Snare Electronic", kw={"bright","synthetic","noise","tight","snap"}},
        snare_alt={type="Snare Electronic", kw={"tight","bright","noise","synthetic"}},
        clap     ={type="Claps & Snaps",    kw={"bright","noise","snap","synthetic","tight"}},
        hh_c     ={type="Hihat Closed",     kw={"tight","synthetic","bright","machine","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"tight","synthetic","bright","machine"}},
        hh_o     ={type="HiHat Open",       kw={"bright","synthetic","noise","tight"}},
        crash    ={type="Crash",            kw={"bright","synthetic","noise","organic"}},
        ride     ={type="Ride",             kw={"bright","synthetic","machine","noise"}},
        perc     ={type="Perc Electronic",  kw={"snap","noise","synthetic","bright","machine"}},
        tom      ={type="Tom",              kw={"organic","bright","punch","noise","deep"}},
      },
    },
    { name="Piano House", default_kw={"bright","lush","warm","organic","layered","room"},
      voices={
        kick     ={type="Kick Electronic",  kw={"punch","deep","bright","organic","sub"}},
        kick_alt ={type="Kick Acoustic",    kw={"punch","room","organic","deep"}},
        snare    ={type="Snare Acoustic",   kw={"bright","room","organic","lush","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","room","organic","warm","flam"}},
        clap     ={type="Claps & Snaps",    kw={"bright","organic","lush","room","layered"}},
        hh_c     ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic","room"}},
        hh_pedal ={type="Hihat Closed",     kw={"bright","acoustic","gold","organic"}},
        hh_o     ={type="HiHat Open",       kw={"bright","acoustic","organic","room","gold"}},
        crash    ={type="Crash",            kw={"bright","room","organic","lush","acoustic"}},
        ride     ={type="Ride",             kw={"bright","gold","acoustic","room","organic"}},
        perc     ={type="Shakers",          kw={"organic","bright","acoustic","lush","warm"}},
        tom      ={type="Tom",              kw={"organic","bright","room","lush","deep"}},
      },
    },
    { name="Balearic", default_kw={"wide","soft","organic","lush","bright","room"},
      voices={
        kick     ={type="Kick Acoustic",    kw={"soft","room","organic","deep","wide"}},
        kick_alt ={type="Kick Electronic",  kw={"soft","organic","sub","deep","lush"}},
        snare    ={type="Snare Acoustic",   kw={"soft","bright","room","organic","wide"}},
        snare_alt={type="Snare Acoustic",   kw={"bright","soft","room","organic","lush"}},
        clap     ={type="Claps & Snaps",    kw={"soft","organic","bright","wide","room"}},
        hh_c     ={type="Hihat Closed",     kw={"soft","bright","acoustic","wide","organic"}},
        hh_pedal ={type="Hihat Closed",     kw={"soft","bright","acoustic","organic"}},
        hh_o     ={type="HiHat Open",       kw={"soft","bright","acoustic","wide","room"}},
        crash    ={type="Crash",            kw={"soft","wide","organic","room","bright"}},
        ride     ={type="Ride",             kw={"bright","soft","acoustic","organic","wide"}},
        perc     ={type="Shakers",          kw={"organic","soft","acoustic","wide","lush"}},
        tom      ={type="Tom",              kw={"soft","organic","wide","room","deep"}},
      },
    },
    { name="Warehouse", default_kw={"heavy","dark","room","organic","deep","punch"},
      voices={
        kick     ={type="Kick Electronic",  kw={"deep","heavy","dark","sub","punch"}},
        kick_alt ={type="Kick Electronic",  kw={"heavy","dark","sub","organic","room"}},
        snare    ={type="Snare Electronic", kw={"dark","heavy","room","organic","layered"}},
        snare_alt={type="Snare Acoustic",   kw={"dark","room","heavy","organic"}},
        clap     ={type="Claps & Snaps",    kw={"heavy","dark","organic","room","noise"}},
        hh_c     ={type="Hihat Closed",     kw={"dark","metallic","tight","machine","noise"}},
        hh_pedal ={type="Hihat Closed",     kw={"dark","metallic","tight","machine"}},
        hh_o     ={type="HiHat Open",       kw={"dark","metallic","heavy","noise"}},
        crash    ={type="Crash",            kw={"dark","noise","organic","room","heavy"}},
        ride     ={type="Ride",             kw={"dark","metallic","organic","room"}},
        perc     ={type="Shakers",          kw={"organic","dark","room","heavy"}},
        tom      ={type="Tom",              kw={"heavy","dark","deep","room","organic"}},
      },
    },
